### ISSUE TITLE
在这里加transform 会造成Stacking Context的问题

### ISSUE THREAD

**Issue by fishercoder** [lihongxun945/jquery-weui#10]
在这里加transform 会造成Stacking Context
.weui_dialog,
.weui_toast {
  -webkit-transition-duration: .3s;
          transition-duration: .3s;
  opacity: 0;
  -webkit-transform: scale(0.9);
          transform: scale(0.9);
  visibility: hidden;
  margin: 0;
  left: 7.5%;
  top: 30%;
}

**Comment by lihongxun945** [comment]
我没明白这样会造成什么bug么？
dialog 本身就是 `position: fixed` 就是一个 stacking context，和我加这个 transform 没关系。
如果是导致了什么bug，你可以把bug描述一下

**Comment by fishercoder** [comment]
具体bug是会导致在华为，联想等一些移动设备上，dialog会弹不出来，把transform和opacity删除掉就正常了，但是也缺失了动画效果

**Comment by lihongxun945** [comment]
你是在微信中用的么？

**Comment by fishercoder** [comment]
微信和嵌入到app里面都会有这个问题，前几天还困扰了我好久好久

**Comment by lihongxun945** [comment]
好的，感谢反馈，其实你应该在issue里面具体描述下这个问题。等我测试一下再看看怎么解决，我暂时手头上没有测试机可以复现问题。

**Comment by lihongxun945** [comment]
我猜测应该跟 Stacking context 没关系，那只是影响内部元素的Zindex的，估计是动画的兼容性问题

**Comment by lihongxun945** [comment]
晕，这个没解决的就别关了。
