### ISSUE TITLE
weui中的weui-dialog冲突

### ISSUE THREAD

**Issue by as0026** [lihongxun945/jquery-weui#102]
weui.css与jquery-weui.css中的weui-dialog样式是由冲突的，这样子就导致我的在使用weui.css中的dialog显示不出来。

**Comment by lihongxun945** [comment]
那不叫样式冲突，而是jQuery weui本来就需要覆盖掉一部分样式。如果发现bug，请先用官方demo测试。确定官方demo也是有问题的再提
