### ISSUE TITLE
建议增加select组件的配置项

### ISSUE THREAD

**Issue by 274665843** [lihongxun945/jquery-weui#108]
select组件能否让用户自定义（可多增加）items数组中的参数项，意思是除了 title 和 value 还要增加其他的item组件配置项，现在items数组中的对象只能有title value两项。。比如我想再增加一个intro，同时onChange事件时我得到obj  然后obj.intro。这样更灵活。

**Comment by lihongxun945** [comment]
下一个版本会增加一个 `origins` 表示未经修改的原始数据。

**Comment by lihongxun945** [comment]
`V0.7.1` 开始，可以通过 `origins` 访问原始数据。

**Comment by 274665843** [comment]
3KS
