### ISSUE TITLE
$.toasta功能建议及问题反馈

### ISSUE THREAD

**Issue by aliang888** [lihongxun945/jquery-weui#109]
var show = function(html, className) {

        className = className || "";
        var mask = $("<div class='weui_mask_transparent'></div>").appendTo(document.body);这里在文档中加入，但在hide中未移除
........
    };

    var hide = function() {
        $(".weui_mask_transparent").hide();这里只是隐藏，然后页面会有N多个这个层
        $(".weui_toast_visible").removeClass("weui_toast_visible").transitionEnd(function() {
            $(this).remove();
        });
    }

功能建议：能不能在hide里面加个回调函数呢？
使用场景：当ajax完成一个操作后，$.toasta一个提示信息，然后在消失的时候，执行某些操作（比如提示隐藏后，我页面要转跳，我现在临时解决办法是把toastDefaults.duration时间设置长点，确保在消失前就转跳）

**Comment by lihongxun945** [comment]
感谢，反馈的两个问题已经在dev分支上解决，会在下一个版本中发布。

**Comment by langyan1022** [comment]
还有就是看到loading  也是toast的一种，然后在隐藏loading的时候其他的toast也会消失

**Comment by lihongxun945** [comment]
@langyan1022  设计的时候并没有考虑loading和toast同时显示的情况，这样不是很奇怪么

**Comment by langyan1022** [comment]
是很奇怪，但是有这样一种场景，在ajax的beforeSend方法中显示加载，complete中关闭加载（这个一般会做成通用的）  ，然后在success中会使用toast显示其他信息，这时候大部分情况，就是success的一闪而过，或者直接就看不到。

所以，这样就有点儿矛盾

所以我觉得toast和loading应该分开来做，

**Comment by lihongxun945** [comment]
那是你写的有问题吧，success的时候先关闭loading，然后再显示 toast 就没问题。你是显示toast再关闭loading吧。

**Comment by langyan1022** [comment]
在ajax的beforeSend方法中显示加载，complete中关闭加载# **（这个一般会做成通用的）**

**Comment by langyan1022** [comment]
通常不会每个ajax调用都写一个beforeSend和complete吧，so，


只是个建议，当然还有很多其他实现方法

**Comment by lihongxun945** [comment]
嗯，只要在显示下一个之前关闭上一个就行了

**Comment by lihongxun945** [comment]
`V0.7.1`  中已经解决重复创建DOM的问题，并且增加了回调函数。
