### ISSUE TITLE
组件展示中关于navbar的一个小BUG

### ISSUE THREAD

**Issue by RunningCoderLee** [lihongxun945/jquery-weui#11]
在navbar组件展示的时候，如果点击【页面一】标签，整个navbar会消失，底部的二维码会上移一段距离，在扩展组件的展示中也存在同样现象

**Comment by lihongxun945** [comment]
初步看是文档的一个样式bug，并不影响组件的使用

**Comment by lihongxun945** [comment]
而且我试了一下，应该跟打开页面之后又调整了窗口宽度有关系。等我明天具体看一下什么原因。

**Comment by airwen1201** [comment]
navbar我也是遇到这个问题，当一个标签的数量超过一个页面时会发生这个问题，我这边，如果cell数量不多，则不会。这问题能修复吗。。。
