### ISSUE TITLE
Calendar 组件如何设置 时间范围呢?

### ISSUE THREAD

**Issue by uywqb** [lihongxun945/jquery-weui#112]
如题

**Comment by lihongxun945** [comment]
文档中有写

**Comment by uywqb** [comment]
IOS 怎么都是NAN呢?

**Comment by lihongxun945** [comment]
@uywqb  这是一个已知bug [https://github.com/lihongxun945/jquery-weui/issues/47](https://github.com/lihongxun945/jquery-weui/issues/47)
