### ISSUE TITLE
日历的最外层div没有设置z-index而被页面上其他元素覆盖

### ISSUE THREAD

**Issue by woshiguabi** [lihongxun945/jquery-weui#115]
jquery-weui.css:1107 
.weui-picker-container 这个类没有设置z-index属性,导致被页面其他元素覆盖

**Comment by lihongxun945** [comment]
picker 是在 `.weui-picker-modal` 上设置了 `z-index: 100`。你看下是不是因为你的版本不是最新版导致的。
