### ISSUE TITLE
图片浏览器如何指定第几张图片打开

### ISSUE THREAD

**Issue by LuckyDing** [lihongxun945/jquery-weui#116]
现在打开的图片都是数组都是第一张，比如我想打开从第三张开始该怎么处理

**Comment by accpdyk** [comment]
我看swiper里有个参数initialSlide ，但是加上后不起作用呢，我正愁这个问题呢

**Comment by lihongxun945** [comment]
这个问题非常好，我会在下一个版本中增加一个参数指定初识图片的位置。

**Comment by lihongxun945** [comment]
`V0.7.1` 开始，可以通过 `initIndex` 参数指定。

**Comment by chenyanwork** [comment]
初始化加载历史图片，有对应的文档说明没啊，找了半天没找到？
