### ISSUE TITLE
新版本预告 V0.7.1

### ISSUE THREAD

**Issue by lihongxun945** [lihongxun945/jquery-weui#119]
- [x] `Toast` 增加了纯文本模式, 增加了关闭回调函数。
- [x] `Popup` 增加了类似picker的非全屏模式。
- [x] `Picker` 增加了 `onChange` 和 `onClose` 参数。
- [x] `Calendar`
  - 修复了在 iOS 上如果没有设置日期会显示 `NAN` 的bug。
  - 增加了 `open`,`close`,`destroy` 等方法，可以通过 `$("xx").calendar("method")` 调用。
- [x] `Select` 在 `onChange` 回调中增加了 `origins` 数据，表示未经修改的原始值。
- [x] `Photo Browser` 增加了一个 `initIndex` 参数，可以指定打开时候默认展示第几张图片。
- [ ] `Photo Browser` 增加手势缩放操作。
- [x] 修复使用zepto导致报错的问题

**Comment by lihongxun945** [comment]
未发布的新版本的代码都在 `dev` 分支上。有很捉急想用新版本的童鞋可以自行切换到 `dev` 分支编译新的代码。

**Comment by zhoudaqing** [comment]
辛苦了，希望能多增加一些滑动、手势效果体验，这方面FrozenUI做的非常不错

**Comment by c20037** [comment]
大大赞楼主!如果0.7.1能把Photo Browser 增加手势缩放操作就好了,对于photo来说不能缩放就感觉缺少点儿什么.

**Comment by c20037** [comment]
- 

- [ ] fdafdsa

- [ ] fdfdsass2

**Comment by lihongxun945** [comment]
新版本已经发布。暂时未完成图片浏览器的手势缩放效果，因为日历组件的一个bug比较严重所以尽早发布此版本。

**Comment by c20037** [comment]
理解！盼缩放功能早日放出！！👍
