### ISSUE TITLE
日历手册bug

### ISSUE THREAD

**Issue by yangweijie** [lihongxun945/jquery-weui#122]
disabled 属性没有

**Comment by lihongxun945** [comment]
没有明白，哪里需要加 `disabled` ? 日历只会给input加上 `readonly`

**Comment by yangweijie** [comment]
参数

你可以在初始化的时候指定如下参数：

> 参数名	类型	默认值	说明
> inputReadOnly	boolean	true	是否自动在 input 元素上加上 readonly 属性
> closeByOutsideClick	boolean	true	点击日历外面关闭
> toolbarTemplate	string	参见源码	Toolbar 的HTML结构
> value	array		默认选择的日期，注意是个数组，比如 ["2016-12-12"]
> disabled	Date Range		禁止选择的日期范围，这是一个 Date Range，请参考下文的说明

这里的 disabled 属性源码 没有实现，  可以来设置日历中 哪些日期不可选中的

**Comment by lihongxun945** [comment]
我发现了，因为这个日历的代码并没有更新，所以现在不支持 `disabled`，我先在文档中删除这个
