### ISSUE TITLE
关于rem的问题，在iphone5和iphone6上html的font-size都是设置的为20px。

### ISSUE THREAD

**Issue by hstarorg** [lihongxun945/jquery-weui#125]
由于jquery-weui设置了html的font-size，而且也用到了rem，我不知道我能否更改这个设置值。

为什么想要更改呢？因为在iphone5和iphone6上html的font-size都是设置的为20px，我就没法用rem来控制元素宽度了。

**Comment by lihongxun945** [comment]
rem是用来进行整页缩放的。如果和你的要求有冲突的话，建议把你的rem规则改成和jqweui一样，不然确实很难办。

**Comment by hstarorg** [comment]
@lihongxun945 我是采用类似淘宝的做法，通过屏幕宽度 / 格子数 来设置html的font-size，实现页面其他部分的等比缩放。

请问在使用jquery-weui的场景下，要满足我这个需求，有什么好的方式推荐么？

Tks~

**Comment by hstarorg** [comment]
后来思考了下，没必要做全站rem缩放，在一个区间用固定的rem值也是可以接受的。

**Comment by Huooo** [comment]
哈喽，上面说的“建议把你的rem规则改成和jqweui一样”这句话，jqweui的适配规则是什么，能稍微解释一下么？我在源码中看见的是400-480范围内的html字体大小的变化，这个字体大小设置是怎么出来的？如果我是640px的应该怎么做呢？因为我们的设计师一般提供的设计图尺寸是640。还请稍微解释一下，非常感谢 @lihongxun945
