### ISSUE TITLE
建议popup增加回调方法

### ISSUE THREAD

**Issue by moioo** [lihongxun945/jquery-weui#127]
建议popup增加显示前及关闭后增加回调访法，如popup显示前我要对popup层的form进行初始化，关闭后我要对录入的数据进行处理

**Comment by lihongxun945** [comment]
这个建议很好，其实现在在 `popup` 上是会触发 `close` 事件的，如果你用JS打开，那么打开和关闭都可以知道了。

我会在下一个版本增加：

- onOpen, onClose 回调函数
- open, close 事件

**Comment by lihongxun945** [comment]
`0.7.2` 增加了 `close` 和 `open` 事件
