### ISSUE TITLE
日期控件问题

### ISSUE THREAD

**Issue by chen19891010** [lihongxun945/jquery-weui#129]
做微信内网页使用日期控件，android 手机显示正常，苹果和wp 手机都显示NaN 这是真么回事?
附代码：
                       var mydate = new Date();
			var month = mydate.getMonth()+1;
			month=month>9?month:"0"+month;
			var date = mydate.getDate();
			var year = mydate.getFullYear();
			function getnow(){
				date = date>9?date:"0"+date;
				var str = "'" + year + "-";
				str += month + "-";
				str += date+"'";
				return str;
			}
			
			
			function getyestoday(){
				date = date-1>9?date-1:"0"+(date-1);
				var str = "'" + year+ "-";
				str += month + "-";
				str += date+"'";
				return str;
			}
	       
		   
			$("#date").calendar({
				value:[getnow()],
				minDate:getyestoday()
			});

**Comment by lihongxun945** [comment]
重复了 https://github.com/lihongxun945/jquery-weui/issues/71
