### ISSUE TITLE
ActionSheet可以增加说明的选项, 不需要添加点击动作, 仅作说明使用, 如图所示

### ISSUE THREAD

**Issue by ireliale** [lihongxun945/jquery-weui#131]
'是否删除该条消息'  就是没有点击动作的说明项
 ![371550040962132306](https://cloud.githubusercontent.com/assets/15493638/15639120/94ac745a-265a-11e6-9bea-b8aee68d0304.jpg)

**Comment by lihongxun945** [comment]
这个建议很赞，我会考虑加上这个功能的。

**Comment by lihongxun945** [comment]
下一个版本增加此功能

**Comment by ireliale** [comment]
哈哈, 太好了, 下个版本大概啥时候发布?

**Comment by lihongxun945** [comment]
@ireliale  本月内发布

**Comment by lihongxun945** [comment]
`0.7.2` 已经增加
