### ISSUE TITLE
Picker,多选或单选，页面滚动

### ISSUE THREAD

**Issue by lonelysun** [lihongxun945/jquery-weui#132]
使用picker，当选项很多时，弹出的picker可以滚动的是ok的，但是想禁掉原来的页面的滚动，我在js里修改尝试当picker触发时给body添加overflow:hidden，关闭后overflow:scroll，结果从微信上打开没有效果，浏览器打开是有效果的，不知道什么原因。

**Comment by lonelysun** [comment]
如果想实现那个效果改怎么做，谢谢

**Comment by lihongxun945** [comment]
如果是手机上实现，那么只要在touchmove的时候，preventDefault即可。但是要注意不要影响picker的滚动。
这个我来实现吧，我在下一个版本实现。

**Comment by lonelysun** [comment]
微信打开h5好像会使overflow失效的，怎么解决？

**Comment by lihongxun945** [comment]
@lonelysun  你确定是overflow失效？我觉得应该是你代码写的有问题

**Comment by lonelysun** [comment]
@lihongxun945 我通过safari打开页面，pc上用chrome打开也ok。就是通过js给body加了一个overflow。

**Comment by lonelysun** [comment]
@lihongxun945 通过远程调试了，最简单的方法，我直接在页面的body上加了overflow，微信打开没有效果。
