### ISSUE TITLE
建议加多个这样的提示控件。

### ISSUE THREAD

**Issue by echobailin** [lihongxun945/jquery-weui#133]
建议加多个这样的提示控件，weui官方有样式提供。
![qq 20160531123024](https://cloud.githubusercontent.com/assets/16745078/15663250/811e689a-272b-11e6-9c6e-316073254e1d.png)

**Comment by lihongxun945** [comment]
OK，这个其实比较简单，下一个版本我加一下。

**Comment by lihongxun945** [comment]
`0.7.2` 已经增加 `toptip` 组件
