### ISSUE TITLE
敬问:大大,图片浏览器的缩放大概什么时候放出?

### ISSUE THREAD

**Issue by icoder2013** [lihongxun945/jquery-weui#134]
一般的功能没做,可能是没有完善. 但是图片没缩放的话,让用户感到产品没有完成! 所以还请大大加油!!另外,请参考photoswipe.com

**Comment by lihongxun945** [comment]
本来计划当前这个版本就发布的，因为这个功能因为比预计的要难，所以推迟了。在一个月内肯定会发布的。

**Comment by icoder2013** [comment]
老大,被用户骂了,能不能先把这个功能放出,非常感谢!

**Comment by lihongxun945** [comment]
不是不放，是确实没有完成这个功能 =。=

**Comment by dd1994** [comment]
图片浏览器现在不是已经可以缩放了？

**Comment by lihongxun945** [comment]
现在已经有了

**Comment by lihongxun945** [comment]
`0.7.2` 已经有缩放功能了

**Comment by dd1994** [comment]
点赞，刚捐了点钱支持作者

**Comment by lihongxun945** [comment]
@dd1994 感谢
