### ISSUE TITLE
Picker能否也新增一个update方法

### ISSUE THREAD

**Issue by SingleOne** [lihongxun945/jquery-weui#136]
如题，picker也需要一个update方法来动态改变values属性啊，还有displayvalue跟value的问题，如果设置了displayvalue，那么选中后文本框里的值也应该是displayvalue才对啊

**Comment by lihongxun945** [comment]
$("#mobile").picker("setValue", ["iPhone 4S"])

**Comment by lihongxun945** [comment]
文档里面有写

**Comment by zzliux** [comment]
他说的update是指原数据都不显示出来吧，如果用setValue的话只是自动滚到那个col上面了而已
