### ISSUE TITLE
picker 三级联动有问题

### ISSUE THREAD

**Issue by endsh** [lihongxun945/jquery-weui#140]
初始化的值不在可选的值中的话，就有问题了。

**Comment by lihongxun945** [comment]
为什么初始值不在可选中值中？ 目前不打算考虑这种奇怪的需求

**Comment by endsh** [comment]
这个倒是不能说是奇怪的需求，而是异常处理、兼容性的问题。你可能偏向于前端，但是如果说，城市这个字段要兼容安卓，ios，微信网页，PC网页各种组件，还有微信、QQ、微博等第三登录获取用户信息时，就肯定会有这种问题存在。

**Comment by lihongxun945** [comment]
这样的话，建议你在初始化city组件之前先把这种兼容处理做了。
我不认为这个是属于city组件应该解决的问题，而且也无法解决：
1. 如果直接无视初识值，那么等价于不设置初始值
2. 如果要根据初始值来选中，那么初始值不在可选列表中无法完美做到选中。

**Comment by endsh** [comment]
这种情况下，应该就无视初始化值。或者至少给出一个warning。因为这样起码也好过三级联动，直接显示1级联动这种奇葩的结果。

**Comment by endsh** [comment]
当然我这边的话，有能力做这种兼容，我们的问题是解决了。只是希望在这上面踩了坑，如果楼主可以做支持的话，以后其他人就不用踩这种坑了。

**Comment by lihongxun945** [comment]
嗯嗯，感谢~
