### ISSUE TITLE
select 组件问题

### ISSUE THREAD

**Issue by weizhihong** [lihongxun945/jquery-weui#141]
1.在使用select的组件时
 一开始选择一切正常，
![image](https://cloud.githubusercontent.com/assets/19730070/15797279/8dff53be-2a44-11e6-83bc-ae7564a520f1.png)
然后关闭组件，然后再次点开，取消选择貌似也是正常的，
![image](https://cloud.githubusercontent.com/assets/19730070/15797280/9621ea5c-2a44-11e6-91ab-984517ed5578.png)
 但是再次点开的时候问题出现了，上次选中的还在没有取消选中。
![image](https://cloud.githubusercontent.com/assets/19730070/15797283/9cb8ed2a-2a44-11e6-938c-6b66ade81ddf.png)

2.
我在API上看到是使用update方法，我是这么写得
                $("#addleader").select("update",{
	    		"value":nameArr.join(','),
	    		"data-values":idArr.join(',')
	    	});
有没有错误？他的值没有发生变化。

**Comment by lihongxun945** [comment]
1. 这个bug我已经复现出来了，非常感谢，我会在下一个版本修复的。
2. 你写错了，传入的第二个参数是完整的配置，也就是应该 `{ items: {xxx} }`

**Comment by lihongxun945** [comment]
@weizhihong  在最新的dev分支上已经修复这个问题，会在下一次正式发布

**Comment by lihongxun945** [comment]
`0.7.2` 修复了这个问题
