### ISSUE TITLE
popup组件的两点小建议

### ISSUE THREAD

**Issue by weidamao** [lihongxun945/jquery-weui#142]
http://lihongxun945.github.io/jquery-weui/dist/demos/popup.html
1、当弹出时加一个背景遮罩效果，比如变灰，不能点击
2、这个三列建议做成四列的，在iphone 4S这样的小屏手机上4列都很好看，现在的3列显得有稀了。。

**Comment by lihongxun945** [comment]
1. 这个建议不错，我会考虑的
2. 这个demo只是一个示例，popup中可以你可以放任意内容。 另外三列的栅格不是我定的，是 `weui` 官方的组件，感觉你可以给他们提一个 Issue

**Comment by 274665843** [comment]
算了不理他们了，我现在是重写的CSS。改成25% 一共四列。。

**Comment by lihongxun945** [comment]
@274665843  是的，其实自己定制一下挺简单的，这种小问题就一行CSS。UI库本来就不是满足 100% 需求的

**Comment by pk-lam** [comment]
支持楼上的需求..我在使用popup半屏做密码输入时,非常需要将背景层遮罩...建议这个尽量加入..

**Comment by lihongxun945** [comment]
@pk-lam  其实popup本来就有一个透明的 `.weui-popup-container` 盖住了整个页面，你只需要一行 CSS 修改一下透明度即可。

**Comment by qidongyou** [comment]
我的popup滑动的时候出现了两个滚动条。求解决方案。

**Comment by wodenwang** [comment]
同上,popup了之后我滑动到底部,其实首先是背后的主页面被滑动到底部.
