### ISSUE TITLE
weui-switch 开关检测状态该怎么写？有封装好的js吗？我照如下写没反应

### ISSUE THREAD

**Issue by Jolly23** [lihongxun945/jquery-weui#144]
<input class="weui_switch" type="checkbox" name="mCheckbox" />

<script type="text/javascript">
    $("input[name=' mCheckbox']").bind('click',function(){
        var objval = ($(this).is(':checked'))?1:0;
        alert(objval);
});

**Comment by lihongxun945** [comment]
$("#input").is(":checked")
