### ISSUE TITLE
搜索框获焦时，弹出光标与样式切换之间有延迟

### ISSUE THREAD

**Issue by RunningCoderLee** [lihongxun945/jquery-weui#15]
搜索框获焦时，光标先出现，之后会有一点延迟，再完成CSS样式的转换，
![11](https://cloud.githubusercontent.com/assets/13218863/13629392/cc3b71b4-e613-11e5-89aa-4cee65a2d287.png)

**Comment by lihongxun945** [comment]
这是iOS本身的延迟，你可以通过 fastclick之类的库来解决
