### ISSUE TITLE
你好在使用calendar时，不设置value还是出现NaN的bug

### ISSUE THREAD

**Issue by sooofunky** [lihongxun945/jquery-weui#153]
使用版本0.7.1在使用calendar时，不设置value还是出现NaN的bug，而且我修改了示例中的代码，去掉后就不能正常显示时间了。调试工具chrome浏览器，在移动环境下设备使用iphone6进行查看的。

**Comment by lihongxun945** [comment]
把你的代码部署到线上 我看看

**Comment by sooofunky** [comment]
您好，我在github上下载的build版，去掉jquery-weui-build\dist\demos\calendar.html中<input class="weui_input" id="date" type="text" >的value属性，使用chrome调试的时候，就是弹出的Nan，加上时间初始值就正常显示了。

**Comment by lihongxun945** [comment]
@sooofunky  确认这个问题是上次没有修复好，你可以先设置初始值解决，下一个版本会修复的

**Comment by sooofunky** [comment]
好的，非常感谢您的回复，也谢谢您分享这个不错的UI。

**Comment by lihongxun945** [comment]
在 `0.7.2` 版本中修复了这个问题
