### ISSUE TITLE
model 弹窗在小屏手机上定位没有做响应式

### ISSUE THREAD

**Issue by yangweijie** [lihongxun945/jquery-weui#154]
![image](https://cloud.githubusercontent.com/assets/1614114/15988795/2258326e-3090-11e6-9d13-002a7eaea8c4.png)

**Comment by lihongxun945** [comment]
因为我不想把对话框放在正中间，而是中间偏上。这种文案很多的情况下你可以自己设置一下 `margin-top`。
但是不建议用 `dialog` 显示大量文案，这种需求最好用 [popup](https://lihongxun945.github.io/jquery-weui/extends#popup)
