### ISSUE TITLE
popup在微信里面滑动有bug

### ISSUE THREAD

**Issue by qidongyou** [lihongxun945/jquery-weui#155]
popup在微信里面滑动有bug.

**Comment by lihongxun945** [comment]
可以具体描述一下问题么？什么bug？

**Comment by liuyu1992** [comment]
我也遇到这个问题。popup在微信里面滑动有bug，苹果手机在滑动的时候滑的很慢很卡，安卓划的很顺畅。

**Comment by liuyu1992** [comment]
加了句，-webkit-overflow-scrolling : touch;
ios也滑动很顺畅了~
