### ISSUE TITLE
你好，时间扩展页面用js取绑定表单的value是空

### ISSUE THREAD

**Issue by VaneHay** [lihongxun945/jquery-weui#158]
html 页面代码
`<input class="weui_input" id="createtime" name="createtime" type="text" placeholder="请选择出行时间">`

获取代码：
`$('input[name="createtime"]').val() `
没有赋默认值的情况下会出现这情况。老大看看

**Comment by VaneHay** [comment]
最新版本，0.7.1的

**Comment by lihongxun945** [comment]
我都没听明白什么意思，没有默认值不是本来就是空的么？

**Comment by cnohng** [comment]
试试$('input[name="createtime"]').attr("data-value")
