### ISSUE TITLE
关于滚动加载和下拉刷新

### ISSUE THREAD

**Issue by sprogjavasprog** [lihongxun945/jquery-weui#160]
1、下拉刷新  一个列表 但我滚动最下面往上面拉时会触发下拉刷新，是否可以添加一个判断只有当滚动条在最顶上是才会触发这个下拉刷新事件

2、滚动加载    滚动加载和下拉刷新配套使用时会报错。。错误是当我滚动加载-----再下拉刷新后滚动加载事件就会失效

**Comment by lihongxun945** [comment]
根据你的描述，我猜测是你的滚动容器有问题，你可以对比下官方demo中容器的设置

**Comment by sprogjavasprog** [comment]
“滚动加载-----再下拉刷新后滚动加载事件就会失效”  问题解决了   当我下拉刷新后要吧loading设置成false  要不然滚动加载不会触发
