### ISSUE TITLE
This library has rewritten the data() function of the jQuery' default implemention

### ISSUE THREAD

**Issue by xiaoyaojian** [lihongxun945/jquery-weui#163]
This library has rewritten the data() function of the jQuery' default implemention,this caused the logic does not going correctly when the parameter called 'key' is undefined

**Comment by dd1994** [comment]
@lihongxun945 为什么要重写 $.fn.data ?

**Comment by lihongxun945** [comment]
@xiaoyaojian @dd1994  这是一个历史遗留问题，我会在下一个版本修复的
