### ISSUE TITLE
请问如何使用picker的setValue方法呢？按照文档无效…

### ISSUE THREAD

**Issue by cloudus** [lihongxun945/jquery-weui#167]
![image](https://cloud.githubusercontent.com/assets/12695053/16142978/653a0df4-349c-11e6-9ad4-08f1325af2d3.png)
请问是如图使用么？测试了，并没有设置到Value.

**Comment by lihongxun945** [comment]
你设置的值 必须是 values中的一个

**Comment by wanghongxi** [comment]
这个回答和没有一样，demo里能增加一个setValue的示例吗？

**Comment by BigForceTaken** [comment]
demo做的有点着急的样子
