### ISSUE TITLE
图片浏览组件建议图片居中显示

### ISSUE THREAD

**Issue by 7PLonG** [lihongxun945/jquery-weui#169]
小图片会靠左显示，居中更符合预期吧

**Comment by lihongxun945** [comment]
这个我先看下

**Comment by yuweiming2016** [comment]
我也遇到了，作者能解决一下吗

**Comment by phpyii** [comment]
这个有人解决了没？

**Comment by phpyii** [comment]
加个样式解决了 
`.weui-photo-browser-modal .photo-container {
    justify-content: center;
}`
