### ISSUE TITLE
日历插件初始化bug

### ISSUE THREAD

**Issue by yangweijie** [lihongxun945/jquery-weui#172]
案例中的日历 value 有值 ，如果为空的话，点击展开没有默认为当天的，都为NaN。
![image](https://cloud.githubusercontent.com/assets/1614114/16185364/d98f9f24-36f5-11e6-8b83-0bf989780900.png)

**Comment by lihongxun945** [comment]
重复 https://github.com/lihongxun945/jquery-weui/issues/153
