### ISSUE TITLE
最近项目中使用JQuery Weui开发微信wap网站出现的问题。

### ISSUE THREAD

**Issue by YacoZhu** [lihongxun945/jquery-weui#174]
当我使用手机浏览器或者微信浏览器打开网页的时候，上下滑动页面，页面就会出现黑色的空白(如图所示)。我该怎么做才能避免这种情况出现？ 求大神解答，很急。

![img_0937](https://cloud.githubusercontent.com/assets/17638503/16191537/50559764-3717-11e6-8e16-fbd838811228.PNG)

**Comment by lihongxun945** [comment]
如果手指滑动的时候，页面已经滚动顶部，那么就会默认出现这个背景。 你可以试试 `touchmove` 事件的时候，如果发现页面已经滚动到顶部，那么 `e.preventDefault()` 来阻止漏出底图

**Comment by YacoZhu** [comment]
好像不行的。 如果这样 我的滚动区域就滑动不了了。

**Comment by lihongxun945** [comment]
你仔细看我说的，是滚动到顶部之后再阻止，你直接阻止了肯定就无法滚动了
