### ISSUE TITLE
radio 单选点击后仅仅是界面变化

### ISSUE THREAD

**Issue by songlai** [lihongxun945/jquery-weui#176]
radio 点击后仅仅是界面变化，实际上 input 的 checked 并没有改变，这还需要自己来处理点击事件或者提交之前要先过滤一遍radio、checkbox 等元素么获取value值么？？

**Comment by lihongxun945** [comment]
我确定值是变化了的，你不要只看 `attr` ，要看 `prop`

**Comment by songlai** [comment]
$("input[name='office_id'][checked]")
界面选中之后， 这个操作是获取不到内容的。就是说没有checked被选中的input项。
chrome 下测试结果。

**Comment by lihongxun945** [comment]
我已经说明了，是你自己取值的方式有问题。`checked` 不是这么取的，你应该先去学一下前端基础知识

**Comment by songlai** [comment]
谢谢！受教了！

我的 解决方法：
`$("input[name='office_id'][checked]")` 
这样是获取不到值的，
```
$("input[name='office_id']").each(function(){
  console.log($(this).prop('checked'));
})
```
这样才可以
