### ISSUE TITLE
图片浏览器第一张显示的图，必须在初始化指定initIndex，设计似乎不太合理

### ISSUE THREAD

**Issue by alansuhe** [lihongxun945/jquery-weui#181]
我觉得应该在open这个动作时，带上index参数

**Comment by lihongxun945** [comment]
这个建议非常好，我会在下一个版本中修改，可以在open的时候设置index

**Comment by alansuhe** [comment]
赞！！！

**Comment by dd1994** [comment]
讲道理的话，应该要像微信朋友圈那样，点击哪个图片就定位到哪个图片

**Comment by dd1994** [comment]
这个要如何实现?只能把 初始化放到 click 的回调函数里才能设置正确的 initIndex?

**Comment by lihongxun945** [comment]
@dd1994 `photos.open(index)` 的方式实现

**Comment by Timnny** [comment]
var pb1 = $.photoBrowser({
             items: imgList,
	   // initIndex: -1
	});
	$(".img_wrap").click(function() {
	      console.log($(this).index())
	      pb1.open($(this).index());
	});
----------------------------
我是这么写的，但是每次刷新之后第一点击，显示的还是第一张图片，但是之后再点击其他的都是正确的。能不能让他像朋友圈一样，第一次也是点击哪一张，就展示那一张。
I write this, but the first click after each refresh is the first picture, but it's right to click on the other later. Can you make it like a circle of friends, which one is the first time you click, and show that one.

**Comment by chenyanwork** [comment]
初始化加载历史图片，有对应的文档说明没啊，找了半天没找到？
