### ISSUE TITLE
图片浏览器 可以支持双击放大吗？

### ISSUE THREAD

**Issue by dd1994** [lihongxun945/jquery-weui#184]
这个也是微信朋友圈那种类似的效果，双击放大。

**Comment by lihongxun945** [comment]
这个建议也很赞，实现起来也很简单，我会在下一个版本实现的

**Comment by dd1994** [comment]
求大大快速，或者我可以写好发个 PR，因为在项目里要用到。。。

**Comment by lihongxun945** [comment]
下一个版本需要等到下个月，如果你急的话，你可以发PR给我，我临时发一个小版本

**Comment by dd1994** [comment]
嗯我先看看代码尝试改一下

**Comment by icoder2013** [comment]
已捐,祝大大有情人终成眷属~~~~~~
双击和单击的习惯如果能和朋友圈一致就好了

**Comment by dd1994** [comment]
大大~~ 你的代码没有注释，问一下这个应该在哪里改，告诉我你原来实现双指缩放的代码在哪里即可~

**Comment by lihongxun945** [comment]
别关啊，我还没加这个功能呢
