### ISSUE TITLE
图片浏览器点击返回按钮的默认行为

### ISSUE THREAD

**Issue by dd1994** [lihongxun945/jquery-weui#185]
在安卓机器上，点击返回按钮，用户的正常期待应该是回到原来的页面，就跟微信朋友圈的行为一样，也就是 pb.close(), 但是现在是直接回到上一个的页面。。。

**Comment by dd1994** [comment]
想了下，这样的话就要在 url 上加个 hash 了，这样不合理

**Comment by AmKang** [comment]
你好，请问你是怎么解决的这个问题，默认返回键返回上一个页面了

**Comment by dd1994** [comment]
@AmKang 不要用这个库了，比较坑，最后我自己重写了。

**Comment by AmKang** [comment]
> @AmKang 不要用这个库了，比较坑，最后我自己重写了。



> @AmKang不要用这个库了，比较坑，最后我自己重写了。

嗯，有些坑，我解决了，就是比较笨的一种方法。谢谢了

**Comment by AmKang** [comment]
var pb= $.photoBrowser({
	  items: [
		"./images/swiper-1.jpg",
                "./images/swiper-2.jpg",
                "./images/swiper-3.jpg"
	  ],
	  onOpen: function(){
                        //图片浏览打开回调
			if(window.history && window.history.pushState) {
				$(window).on('popstate', function() {
					var hashLocation = location.hash;
					var hashSplit = hashLocation.split("#!/");
					var hashName = hashSplit[1];
					if(hashName !== '') {
						var hash = window.location.hash;
						if(hash === '') {
							pb.close();
						}
					}
				});
				window.history.pushState('forward', null, './#forward');
			}
			},	
		onClose: function(){
                        //图片浏览关闭回调
			console.log("pb browser close"); 
		}
	});

**Comment by AmKang** [comment]
`var flag=false;	
var pb= $.photoBrowser({
	 items: [
			"./images/swiper-1.jpg",
            "./images/swiper-2.jpg",
            "./images/swiper-3.jpg"
			],
	 onOpen: function(){
			//图片浏览打开回调
			window.history.pushState('forward', null, '#forward');
			flag=true;
			},	
	onClose: function(){
            //图片浏览关闭回调
            flag=false;
			console.log("pb browser close"); 
			}
	});
	$(window).on('popstate', function() {
		if(flag)
			pb.close();
		
	});`

**Comment by AmKang** [comment]
var flag=false;	
var pb= $.photoBrowser({
	 items:[
			"./images/swiper-1.jpg",
            "./images/swiper-2.jpg",
            "./images/swiper-3.jpg"
			],
	 onOpen: function(){
			//图片浏览打开回调
			window.history.pushState('forward', null, '#forward');
			flag=true;
			},	
	onClose: function(){
            //图片浏览关闭回调
            flag=false;
			console.log("pb browser close"); 
			}
	});
	$(window).on('popstate', function() {
		if(flag)
			pb.close();
		
	});

**Comment by AmKang** [comment]
![image](https://user-images.githubusercontent.com/43641341/51469051-5558b200-1dab-11e9-89ce-ae96838253fb.png)

**Comment by dd1994** [comment]
@AmKang 还是要劝你不要用了，这个库还有很多其它坑
