### ISSUE TITLE
jquery weui 压缩css样式后，alert confirm效果没有了

### ISSUE THREAD

**Issue by zhujinhu21** [lihongxun945/jquery-weui#19]
我用mvc bundle压缩
  bundles.Add(new StyleBundle("~/Content/weui").Include(
           "~/js/jquery-weui/css/weui.css",
           "~/js/jquery-weui/css/jquery-weui.css"
           ));

**Comment by zhengnz** [comment]
.weui_dialog的z-index没了，其实就是weui.min.css和weui.css不同步

**Comment by lihongxun945** [comment]
下一个版本会修复这个问题。原因是 `weui.min.css` 在压缩的时候改变了 `z-index` 值，在下一个版本发布之前，你可以暂时用 `weui.css` 来解决这个问题

**Comment by lihongxun945** [comment]
V0.6.0 已经解决
