### ISSUE TITLE
city picker问题

### ISSUE THREAD

**Issue by sndwow** [lihongxun945/jquery-weui#200]
有个意见反馈下，是关于city picker。
因为做商城要涉及到运费的计算，所以要在数据库中查询客户所选地址的省市县所设置的运费，再根据运费设定最终的订单金额。但是jquery weui的地址是没有编号，而是中文，所以只能对比中文，最新的版本v0.7.2更改了一些直辖市的名称，导致有些订单找不到合适的运费。

个人意见：
根据http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/201504/t20150415_712722.html
提供的行政区划代码，给省市县添加代码，给部分县/区内的【其他】选项添加自定义的代码，例如900000。

这样可以在做运费计算的时候根据代码来判断，而省市县名称仅用于客户展示

**Comment by 613660067** [comment]
附意,现在项目也需要这个功能!

**Comment by lihongxun945** [comment]
因为没有找到合适的数据源，手工整理数据需要一些时间，所以在 `V0.8.0` 中暂时不会增加城市代码。

**Comment by lihongxun945** [comment]
哪位找到了很不错的JSON数据可以告诉我

**Comment by 613660067** [comment]
格式要什么样的?说一下,有时间的话应该可以造一个

**Comment by lihongxun945** [comment]
@613660067 格式保持和现在源码中的 `city-data.js` 里面一样就可以了，其中每一条数据都增加一个 `code` 字段即可。

**Comment by lihongxun945** [comment]
v0.8.1 已经添加了地区编码
