### ISSUE TITLE
tabbar不能实现底部固定

### ISSUE THREAD

**Issue by qq57941500** [lihongxun945/jquery-weui#204]
首先感谢这么好的jquery-weui，为我首次开发移动web帮了大忙了。
遇到一个问题，tabbar无法实现浏览器底部固定。
我用tabbar做了一个工具栏，效果如下。
[效果图](http://files.cnblogs.com/files/teamleader/jquery_weui_tabbar.gif)
不知道是我没用好，还是tabbar就是不支持这个底部固定。
希望哪位大神帮帮忙。

**Comment by qq57941500** [comment]
加了这么一个style，勉强搞定了。
 style="position:fixed; bottom: 0; "
<div class="weui_tabbar" style="position:fixed; bottom: 0; ">
但是这个办法在弹出的popup中失效 :(
<div id="full" class="weui-popup-container">

**Comment by lihongxun945** [comment]
这种基本问题还是在QQ群里讨论吧

**Comment by fengjx** [comment]
@qq57941500 遇到同样的问题，请问解决了吗？
