### ISSUE TITLE
内联日历数据错误

### ISSUE THREAD

**Issue by sunmingmingcn** [lihongxun945/jquery-weui#208]
data值错误，和选中的值差一个月！
目前已经自己在JS里加一解决，等待中。

**Comment by lihongxun945** [comment]
感谢反馈

**Comment by lihongxun945** [comment]
你的意思是在 `onChange` 回调函数中，时间戳转换之后会差一个月么？

**Comment by lihongxun945** [comment]
不要在 dom上去取值，那是内部用的，应该在 `onChange` 事件中取值，或者在 `input` 上取值。
而且，在JS中 `month` 本来就是从 0 开始的，不是bug
