### ISSUE TITLE
使用weui开发的公众号,客户端打开特别慢

### ISSUE THREAD

**Issue by raydl007** [lihongxun945/jquery-weui#217]
请问其他人有没有这种情况,是weui的问题还是微信的问题?有谁知道怎么解决么

**Comment by lihongxun945** [comment]
请描述清楚你的问题，是网络请求慢还是操作的时候卡？
如果是网络请求慢，那么具体是哪几个文件慢
如果是操作卡，那么请描述功能和操作

**Comment by raydl007** [comment]
@lihongxun945 首先可以确定不是操作卡,但是否是请求慢就不好判断了.具体情况是这样的,第一次打开我们开发的公众号,需要等待很久的时间,最终加载出来的页面是没有样式的,之后一段时间内打开的速度就很快了,这应该是因为缓存了第一次的js/css脚本.不过使用微信web开发者工具打开同一个页面并没有发现有需要很长时间下载的内容

**Comment by lihongxun945** [comment]
你没有profile工具可以看下每一个请求的时间么？

**Comment by lihongxun945** [comment]
如果你无法描述具体的问题，建议先去QQ群问下，而不是直接提issue，这样并没有意义

**Comment by raydl007** [comment]
好的,谢谢,的确不太好描述,我个人觉得现在现象很奇怪
