### ISSUE TITLE
Picker的条目多时会向下偏移

### ISSUE THREAD

**Issue by hs-rainight** [lihongxun945/jquery-weui#23]
Picker的条目多时会向下偏移，十几个就完全空白了。
电脑上看没事，手机上有问题。
手机：三星A5、安卓4.4.4。

**Comment by Hackerzzm** [comment]
在微信自带浏览器和UC浏览器中测试相同问题，手机自带webkit内核的浏览器就没问题

**Comment by lihongxun945** [comment]
V0.6.0 已经解决
