### ISSUE TITLE
tabbar 如果不引入demo.css样式有问题

### ISSUE THREAD

**Issue by peter123456789** [lihongxun945/jquery-weui#250]
bug反馈： 
tabbar 如果不引入demo.css样式有问题
<link rel="stylesheet" href="css/demos.css">
版本 V0.8.0

demo.css设计时 应该不是必须的吧 ？？

**Comment by lihongxun945** [comment]
麻烦请把问题描述清楚，什么叫`有问题`？

**Comment by peter123456789** [comment]
bug反馈： 
 tabbar.html 如果不引入demo.css样式， 底部 weui_tabbar 会贴到顶部，位置不会固定在底部。

版本 V0.8.0

**Comment by lihongxun945** [comment]
这个样式要根据自己的需要加，因为这个会影响整个页面的高度。
