### ISSUE TITLE
tabbar 和 select 覆盖

### ISSUE THREAD

**Issue by peter123456789** [lihongxun945/jquery-weui#251]
底部tabbar 和select组合使用 会出现select最下面一条覆盖情况

**Comment by icoder2013** [comment]
发现同样的问题

**Comment by cvstore** [comment]
这的确是个问题。 自己使用的话，先暂时把select样式的 z-index 设为大于500吧。比如501，600都可以

**Comment by lihongxun945** [comment]
V0.8.3 会修复此问题
