### ISSUE TITLE
select 组件可以在弹出来的时候动态的修改选中值

### ISSUE THREAD

**Issue by moto72** [lihongxun945/jquery-weui#256]
可以使用onOpen 这个方法来修改 对象中选中的值吗？ 我修改  titles 和 values 均没有达到效果
onOpen:function(p){
 p.data.titles= "";
 p.data.values="";
}

**Comment by lihongxun945** [comment]
请仔细看文档，有专门更新的方法。这种问题不要在这里提。

**Comment by moto72** [comment]
@lihongxun945

**Comment by moto72** [comment]
@lihongxun945 我看到文档有说“同时设置了 value 和 data-values 两个值”，但是我在使用onOpen:function(){}方法中给input  赋值value和data-values，第一次点开的时候列表没有被选中，点击确定后在第二次点开的时候才显示选中状态

**Comment by lihongxun945** [comment]
@moto72 你看下你的版本是不是最新的

**Comment by moto72** [comment]
@lihongxun945 从 bootcss 的  cdn 引用的 0.8版本
