### ISSUE TITLE
当前版本下，alert不居中（V0.5.1），weui本身OK。另外文本框被输入法遮挡，通病。

### ISSUE THREAD

**Issue by cnyyk** [lihongxun945/jquery-weui#27]
看图便知

![qq20160327-3 2x](https://cloud.githubusercontent.com/assets/275233/14066007/89dd495c-f471-11e5-96cf-7080d8bb288e.png)

![qq20160327-4 2x](https://cloud.githubusercontent.com/assets/275233/14066005/7876c9a4-f471-11e5-8644-2bb4d0ee66ad.png)

![qq20160327-5 2x](https://cloud.githubusercontent.com/assets/275233/14066009/8ec05dba-f471-11e5-8ccb-fc44a3183589.png)

另外文本框被输入法遮挡，通病。
看这里：https://github.com/weui/weui/issues/15#issuecomment-202083116

![7 pic](https://cloud.githubusercontent.com/assets/275233/14066006/7ad89bdc-f471-11e5-994f-836ab950463d.jpg)

**Comment by lihongxun945** [comment]
只是在屏幕很宽的情况下不居中，在手机上是没问题的

**Comment by cnyyk** [comment]
手机上竖屏确实没问题，横屏没测试过。

但我认为这个终究是个BUG。

如果在 iPad Pro 12 寸下，横屏，就会同样的问题重现了。

**Comment by lihongxun945** [comment]
是的，我下次修复这个问题
