### ISSUE TITLE
在指定initIndex或open(index)情况下，照片浏览器向后滑动翻页仍然会直接跳到最后。

### ISSUE THREAD

**Issue by alansuhe** [lihongxun945/jquery-weui#271]
0.8.1版本。
1.不指定index初始值的情况下正常；
2.第一到第二张滑动是正常的，第三张后才会出现，所以要用超过5张的图片才能看出bug效果。

**Comment by alansuhe** [comment]
我发现问题了，initIndex不能用字符型，必须转换parseInt，是我自己的问题，sorry

**Comment by lihongxun945** [comment]
弱类型语言就是容易出现这种问题
