### ISSUE TITLE
City Picker部分市级无城区导致编码出现错误

### ISSUE THREAD

**Issue by sndwow** [lihongxun945/jquery-weui#276]
例如：河南省，济源市
这个地址没有地区，导致input内的data-code和data-codes错误的使用了上一个拥有地区的地址编码

建议将没有地址的区域设置为0或-1，以便区分

测试地址：http://jqweui.com/dist/demos/city-picker.html

<img src="http://jiyouo2o.lovegxlz.com/public/city_picker.jpg">

**Comment by lihongxun945** [comment]
感谢反馈，测试了一下确实是一个bug

**Comment by lihongxun945** [comment]
v0.8.2 已经修复

**Comment by sndwow** [comment]
作者神速啊。这个BUG已经修复了
但是[https://github.com/lihongxun945/jquery-weui/issues/279](url)
这个问题还是依旧，您可以试一下初始化地址为“河南省 济源市”
例如：
HTML:
<input class="weui_input" id="address" type="text" value="河南省 济源市">

JS:
$("#address").cityPicker({
        title: "收货地址",
        onChange: function (picker, values, displayValues) {
            console.log(displayValues);
        }
    });

然后点击地址栏，会发现无论选择省份还是城市，都无法触发多级联动。
<img src="http://jiyouo2o.lovegxlz.com/public/12.jpg">

**Comment by lihongxun945** [comment]
晕了，我还以为是同一个问题。

**Comment by sndwow** [comment]
不是同一个。因为没有地区信息，所以https://github.com/lihongxun945/jquery-weui/issues/279里才建议用code来进行初始化。
话说，初始化的时候，用省市区字符串初始化，耗时不应该是比code多麽。
例如初始化的时候，传入省市区信息，同时也传入data-code和data-codes，在触发citipicker的时候，使用code初始化。

**Comment by lihongxun945** [comment]
这样初始化太麻烦了，其实最好的方式是只用 `data-code` 的值初始化，也就是选择的地区的编码，但是这样做就需要根据地区查找城市和省份，目前的数据结构不太好做
