### ISSUE TITLE
weui.css  sourceMappingURL问题

### ISSUE THREAD

**Issue by chang0022** [lihongxun945/jquery-weui#278]
这个严格不是BUG，就是你提供的 weui.css 非压缩版本，底部的  sourceMappingURL会导致样式重复，冲突。这个问题是我们非前端设计妹子用的时候，样式有问题，她用的weui.css版本。

**Comment by lihongxun945** [comment]
我没有明白什么叫“样式重复冲突“？ sourceMap 本身是很标准的用法
