### ISSUE TITLE
dialog弹出格式化html问题

### ISSUE THREAD

**Issue by Craft24** [lihongxun945/jquery-weui#29]
场景：注册时，阅读协议时让弹出注册协议，注册协议从数据库中读取，会有br、strong、span等之类的html标签
1、用modal自定义，confirm自定义的都不行，弹不出，要么就报非法字符结尾巴
2、用原生的weui_dialog写可以输出格式化的字符，但是弹不出，将jquery-weui.css中的weui_dialog的样式调整为<style>.weui_dialog{opacity: 100;visibility:visible;}</style>可以正常用jquery的show和hide了
注：error 图片传不上去了，群里有几个图片

**Comment by lihongxun945** [comment]
1. 非法字符串结尾这种语法问题不要在这里提出来，谢谢。
2. 你可以先对比官方demo的代码，weui有一个已知问题就是他的 `weui.min.css` 由于压缩的时候更改了 `z-index` 会导致和 `jquery-weui.css` 有冲突，用 `weui.css` 就行了。

**Comment by Craft24** [comment]
1、的确是语法问题。但是输出格式化html的情形有，这种语法问题是js接收格式化字符造成的，如果用原生div可以避免，看jquery-weui.js中好像写的是append接收的js变量，js变量承载不了格式化字符好像，js学的比较渣。
2、谢谢了

**Comment by icepole-jon** [comment]
@lihongxun945 .weui_mask 的z-index貌似多了一个0？
