### ISSUE TITLE
同步 weui v1.0 版本

### ISSUE THREAD

**Issue by lihongxun945** [lihongxun945/jquery-weui#298]
weui 最近更新了 v1.0 版本，变化命名方式，并新增好几个组件。 jqweui 下一个版本会同步到 v1.0

更新详情：https://github.com/weui/weui/blob/master/CHANGELOG.md

**Comment by icoder2013** [comment]
老大,新版本预计啥时候出?

**Comment by endsh** [comment]
这就坑爹咯~~

**Comment by liuchungui** [comment]
请问什么时候更新？

**Comment by wenzhili** [comment]
请问大概什么时候更新？

**Comment by cczw2010** [comment]
新版本预计啥时候出? 现在好久了. 再不出只能自己封装了.

**Comment by lihongxun945** [comment]
抱歉，最近公司事情比较多，所以暂时没时间同步到 weui V1.0，不过在这之前我会先在当前版本上修复几个重要的bug

**Comment by linapex** [comment]
求版本升级~ up up up!
