### ISSUE TITLE
搜索框操作请教

### ISSUE THREAD

**Issue by zhengnz** [lihongxun945/jquery-weui#30]
请问clear和cancel如何操作？似乎没法自定义click事件

**Comment by Caijt** [comment]
如果搜索框里有内容时，点击其它地方不恢复样式比较好

**Comment by Caijt** [comment]
我觉得在jquery-weui.js的1020行判断一下文本框中是否有值，如果没值那blur事件就会恢复样式
像下面这样，就跟官方的效果一样了
if($(e.target).val().length<=0){
   $(e.target).parents(".weui_search_bar").removeClass("weui_search_focusing");
}

**Comment by Caijt** [comment]
再改成这样，后面那个clear按钮就会清空值并自动恢复样式
$(document).on("click", ".weui_search_bar label", function(e) {
    $(e.target).parents(".weui_search_bar").addClass("weui_search_focusing");
  }) 
  .on("blur", ".weui_search_input", function(e) {
    if($(e.target).val().length==0){
      $(e.target).parents(".weui_search_bar").removeClass("weui_search_focusing");
    }
  }).on("click",".weui_icon_clear",function(e){
    $(e.target).prev().val("").parents(".weui_search_bar").removeClass("weui_search_focusing");
  })

**Comment by zhengnz** [comment]
@Caijt 这个方法不错， @lihongxun945 希望能加入到代码中

**Comment by lihongxun945** [comment]
@Caijt  你的这个建议很好，确实是我写太粗糙了，已经更新了 `blur` , `cancel` 和 `clear` 的 逻辑，下一个版本会发布。

**Comment by lihongxun945** [comment]
V0.6.0 已经更新了逻辑，但是目前发现 `cancel` 逻辑还是有些问题，我在下一个版本再更新一下
