### ISSUE TITLE
V0.82的datetime-picker发现两个bug

### ISSUE THREAD

**Issue by yuweiming2016** [lihongxun945/jquery-weui#301]
1、分钟数只有1~58分，少了一次循环（第59次）
2、将分钟数调整成每30分钟一次的话（['00','30']）,首次选择'00',是选择不上，首次选择'30'或者第二次选择'00'都没问题。经查看chrome控制台无任何报错。
![ffg6 g_ a kvb0ka73h 7](https://cloud.githubusercontent.com/assets/22490427/18902103/200addfc-8583-11e6-8252-0a706a8fac8d.png)

**Comment by yuweiming2016** [comment]
第二个bug总的来说，就是设置成30分钟一次的话，首次无法选择‘00’,再次选择就行了

**Comment by yuweiming2016** [comment]
请问作者，这个问题能否帮忙确认下是不是我自己的问题？
把分钟设置成只有00，30两个选择（我们公司有业务需求，时间间隔为30分钟），首次会选不上，第二次才能正确操作上

**Comment by lihongxun945** [comment]
@yuweiming2016  你的初始值设置是对的吗？

**Comment by yuweiming2016** [comment]
言川，你好，demo我是从线上扒下来修改的（http://jqweui.com/dist/demos/datetime-picker.html），我稍后上传一个demo，麻烦你帮忙运行看看。

**Comment by lihongxun945** [comment]
@yuweiming2016  好的，你把demo部署到线上 我看看

**Comment by yuweiming2016** [comment]
@lihongxun945 ，我没有对外的服务器，抱歉，无法部署，附带有两个截图说明。我用demo重现了，重现条件如下：

1、无默认值
2、times经过重写，如：
![image](https://cloud.githubusercontent.com/assets/22490427/19258610/f0f7f328-8fab-11e6-8f51-cd5ce8ab1c30.png)


不重写times，即使无默认值，也不会有问题
![image](https://cloud.githubusercontent.com/assets/22490427/19258627/1d45d10c-8fac-11e6-918f-cdd275709c6c.png)

以下是重现截图
![1-](https://cloud.githubusercontent.com/assets/22490427/19258656/714a0548-8fac-11e6-9e4f-719305bb4c09.png)
![2-](https://cloud.githubusercontent.com/assets/22490427/19258657/7170fd42-8fac-11e6-8e1d-6045eb8d4f7e.png)

**Comment by yuweiming2016** [comment]
附件demo发你邮箱了

**Comment by lihongxun945** [comment]
@yuweiming2016 自定义minutes的情况下必需要给默认值

**Comment by bfbd888** [comment]
V0.82，datetime-picker，补充两个遇到的问题。
1、设置min和max之后，年份仍显示很大的一个区间。
虽然只能选择min和max之间的年份，但显示的内容还是不太符合预期，如果能只显示min和max之间的年份就更好了。建议在defaults中给min和max一个初始的默认值，然后年份列表从min和max之间取。
2、onChange消息函数的第二个参数会在滑动过程中跳出min和max的范围。
经测试，input控件的val()不会跳出范围，自己适配了一下。
`                        onChange: function () {
                            setTimeout(function(){
                                vm.start_day = $('#date_pop_input').val();
                            },0);
                        }`
