### ISSUE TITLE
多次执行加载动画后页面中的元素没有被移除

### ISSUE THREAD

**Issue by Ttou** [lihongxun945/jquery-weui#302]
![test](https://cloud.githubusercontent.com/assets/4298437/18902112/32bf5504-8583-11e6-8a23-578cd3875f04.png)

**Comment by yuweiming2016** [comment]
是的，我也发现了

**Comment by lihongxun945** [comment]
确定是做了移除操作的，如果发现没有被移除，可能是如下两个原因导致的：
1. 可能是在特定的环境下有bug，可以提供一下你们重现出来的环境么
2. 可能是CSS动画被影响了，现在是在动画结束的时候移除的，如果消失动画不正常会导致无法被移除

**Comment by Ttou** [comment]
我是在vue中使用
![002](https://cloud.githubusercontent.com/assets/4298437/19219487/fa83a9f2-8e46-11e6-954e-66e8fa27dae3.png)

**Comment by yuweiming2016** [comment]
奇怪，我自己写了一个简单的demo，居然发现是会移除的
$.hideLoading();时会自动移除

**Comment by lihongxun945** [comment]
@yuweiming2016  你看源码就知道，在 `transitionEnd` 的时候会自动删除的。如果隐藏了但是没有删除，基本可以确定是 `transitionEnd` 事件没有触发导致的。

**Comment by yuweiming2016** [comment]
发现规律了，显示跟隐藏相隔太短，就会删除失败
$("#show-loading").click(function(){
   	       $.showLoading("正在加载...");
               $.hideLoading();
}

以下能正确删除（延迟100毫秒）：
$("#show-loading").click(function(){
	       $.showLoading("正在加载...");
		 setTimeout(function(){
		       $.hideLoading();
		  },100);
	   });


我之前的场景是：ajax请求，beforeSend里显示，success里隐藏，由于请求太快，所以删除失败
![image](https://cloud.githubusercontent.com/assets/22490427/19225344/77197aa6-8ecd-11e6-8931-435847d99eff.png)

**Comment by Ttou** [comment]
把隐藏放在延迟操作里的确有用，但是点太快还是会出现问题

**Comment by lihongxun945** [comment]
我会在下一个版本解决这个问题的
