### ISSUE TITLE
非常严重的bug，tabbar底部导航和表单form的input 在同一个页面时冲突，导致input不能输入元素。

### ISSUE THREAD

**Issue by 1suming** [lihongxun945/jquery-weui#306]
错误代码： 把http://jqweui.com/components#tabbar 中的底部导航的tabbar代码和示例中的form代码放在同一个页面。打开这样页面会发现表单input不能输入了，非常奇怪的bug。
 
-运行环境：0.8.2 

 重现步骤 : 可以重现

**Comment by ikabb** [comment]
请问这个问题你是怎么解决的
