### ISSUE TITLE
CityPicker 没有区县，无法获取值

### ISSUE THREAD

**Issue by jackchain** [lihongxun945/jquery-weui#309]
官方的代码也有这样的问题，麻烦尽快解决下bug
比如选择-广东省-东莞市，下面没有区县，然后点击确认的时候无法将选中的值填充到文本框，再次打开也有问题。

**Comment by jackchain** [comment]
我把所有不带区县的城市，都默认加了一个“市区”的三级选项，临时解决这个bug问题

**Comment by dongfo** [comment]
中山市也有会有这个问题，全国就这两个市下面直接到镇了。

**Comment by zhangwei900808** [comment]
我也是遇到这个问题，加市区确实有点勉强了，应该通过代码规避这个问题的

**Comment by lihongxun945** [comment]
V0.8.3 会解决这个问题的。
