### ISSUE TITLE
android设备picker待选value项过多时，弹出层的选中框会被顶到下边去

### ISSUE THREAD

**Issue by ZivZhao** [lihongxun945/jquery-weui#32]
问题：value项过多时，那个选中焦点框会被挤到屏幕下边去，无法看到
建议：
1.现在需按住value区域才能滑动选择，按住旁边不可以，会带动主页面滚动，能否做成跟IOS的select一样,在弹出的区域都可以滑动，比较符合操作习惯
2.现在只有values和displayvalues，有多个值关联使用的情况，能否增加绑定，或者回调函数

**Comment by RunningCoderLee** [comment]
picker能不能做成点击input后自动将这个input移动到弹出的picker上方？
还有如果已经弹出系统自带键盘的时候点击触发picker，自带键盘不会被隐藏，这个能不能也更新一下，辛苦作者

**Comment by lihongxun945** [comment]
@RunningCoderLee  你这是一个不同的问题，不要写在别人的issue里面，单独提出来。

**Comment by lihongxun945** [comment]
picker 我在 `dev` 分支上已经做了修复，有兴趣的切换到 `dev` 分支验证下

**Comment by lihongxun945** [comment]
V0.6.0 已经解决
