### ISSUE TITLE
地址选择器「city-picker」选 『广东省』『东莞市』，一直选不中

### ISSUE THREAD

**Issue by pooy** [lihongxun945/jquery-weui#324]
- 错误代码：没有报错
- 运行环境：安卓，ios, 微信开发工具上调试，包括您的网站上测试均选不中
- 重现步骤  直接选广东省，东莞市
- 期望结果，能选中东莞
未报错！

**Comment by zhanglc** [comment]
hmm....因为他没有第三级县区的选择，你改一下city.js ,根据格式加一个东莞市区在东莞市的下面，然后应该可以了
`{
        "name":"东莞市",
        "code":"441900",
        "sub":[
           {"name":"市区","code":"441901"}
        ]
      },`

**Comment by pooy** [comment]
哈哈 多谢🙏我下午试试看。发自网易邮箱大师
            在2016年12月06日 11:42，zhanglc 写道:hmm....因为他没有第三级县区的选择，你改一下city.js ,根据格式加一个东莞市区在东莞市的下面，然后应该可以了
{ "name":"东莞市", "code":"441900", "sub":[ {"name":"市区","code":"441901"} ] },

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lihongxun945/jquery-weui","title":"lihongxun945/jquery-weui","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/lihongxun945/jquery-weui"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zhanglc in #324: hmm....因为他没有第三级县区的选择，你改一下city.js ,根据格式加一个东莞市区在东莞市的下面，然后应该可以了\r\n`{\r\n        \"name\":\"东莞市\",\r\n        \"code\":\"441900\",\r\n        \"sub\":[\r\n           {\"name\":\"市区\",\"code\":\"441901\"}\r\n        ]\r\n      },`"}],"action":{"name":"View Issue","url":"https://github.com/lihongxun945/jquery-weui/issues/324#issuecomment-265052585"}}}

**Comment by pooy** [comment]
good！ 已经解决，多谢！
 
 
------------------ Original ------------------

**Comment by zhangwei900808** [comment]
我也遇到这个问题，加市区是不是有点勉强了，应该还是改代码部分吧，应该检测到这个问题改代码

**Comment by pooy** [comment]
就是添加了一段代码就好了。
 
 
------------------ Original ------------------

**Comment by lihongxun945** [comment]
v0.8.3 已经解决
