### ISSUE TITLE
我在将picker destroy之后重新初始化picker，但是初始化失败了，怎么解决

### ISSUE THREAD

**Issue by Shanxian** [lihongxun945/jquery-weui#328]
## 这个是的代码
`$("#pic").picker({
            title: "请选择使用时间",
            cols: [{
               textAlign: 'center',
               values: [
                  '1', '2', '3'
               ]}
            ]
         });`
`$("#pic").picker('destroy');`
`$("#pic").picker({
            title: "请选择使用时间",
            cols: [{
               textAlign: 'center',
               values: [
                  '4', '5', '6'
               ]}
            ]
         });`
### 其实我想要的结果就是将picker里展示的数据换掉，这个方法不好使，或者有更好的方法吗？

**Comment by nicole520** [comment]
我也有相同的问题

**Comment by lihongxun945** [comment]
Thanks, 下一个版本会修复。

**Comment by chenqunming** [comment]
0.8.3版本修复了吗
