### ISSUE TITLE
发现cityPicker.js代码第11086行代码问题

### ISSUE THREAD

**Issue by zhangwei900808** [lihongxun945/jquery-weui#332]
## cityPicker.js代码第11086行代码你只设置了.attr属性，并没有使用data属性，这样一来别人就无法通过data来获取了

![1](https://cloud.githubusercontent.com/assets/4385154/21445647/9524c394-c8f6-11e6-9e51-a414ce3dafb4.png)

**Comment by greedying** [comment]
这个和data是等价的吧

**Comment by zhangwei900808** [comment]
怎么可能等价呢

**Comment by TechQuery** [comment]
@greedying http://jquery123.com/data

**Comment by greedying** [comment]
@TechQuery  谢谢。

**Comment by greedying** [comment]
@zhangwei900808  部分版本的jquery，基本等价
