### ISSUE TITLE
同步 WEUI V1.1.0 进展

### ISSUE THREAD

**Issue by lihongxun945** [lihongxun945/jquery-weui#335]
目前正在进行 weui v1.1.0 的更新，进度如下：

- [x] jqweui 现有组件更新
- [x] weui v1.0.0 新增组件
- [x] jqweui 拓展组件改用 BEM命名 (部分更新)
- [x] 更新文档(保留旧版文档)

预计 本周四发布一个预览版本
具体进展，可以参见 `dev` 分支

**Comment by lihongxun945** [comment]
已发布 v1.0.0-rc.0

**Comment by chengyifly** [comment]
👍！！请问可以用zepto替代jq吗？

**Comment by xynocry** [comment]
@chengyifly   那你还不如用微信原版的，

**Comment by xynocry** [comment]
@lihongxun945 希望能坚持住，一直更新下去

**Comment by aetherwu** [comment]
WEUI这命名更改太蛋疼了……

**Comment by lottepie** [comment]
@chengyifly 我用的就是zepto

**Comment by openpython** [comment]
进来赞个，总算与webui同步了，支持个！

**Comment by sndwow** [comment]
支持

**Comment by lihongxun945** [comment]
目前没有发现重大bug，这周末会更新 v1.0.0 正式版
