### ISSUE TITLE
Select关闭时，onClose函数会调用2次！！

### ISSUE THREAD

**Issue by tangweixin** [lihongxun945/jquery-weui#336]
# 如题

![image](https://cloud.githubusercontent.com/assets/897400/21569482/22daa76a-cef8-11e6-9ce8-1cd0633606f4.png)

## 建议增加取消和确认按钮！

![image](https://cloud.githubusercontent.com/assets/897400/21569547/bf9ebb90-cef8-11e6-9508-8e872865c8d9.png)

**Comment by lihongxun945** [comment]
onClose 的bug会在下一个版本解决。

**Comment by lihongxun945** [comment]
fixed v1.0.0
