### ISSUE TITLE
Calendar组件在微信内置浏览器中存在问题

### ISSUE THREAD

**Issue by wcjemail** [lihongxun945/jquery-weui#34]
Calendar组件在微信内置浏览器中存在问题，能弹出DIV层，但无日期内容可选。在安卓机手机UC浏览器中出现同样问题，但在手机端QQ/360/谷歌浏览器可以。同时，在微信web开发者工具中也可以。

**Comment by liqingzhu** [comment]
大神辛苦了！

**Comment by ww380459000** [comment]
datetime也有类似的情况

**Comment by ww380459000** [comment]
有的机型会只出现年份，其他的都是空白显示

**Comment by zhognsheng** [comment]
同样遇到这个问题,苹果手机可以用,同事的安卓手机不能用,安卓版本是4.4.4和4.4.2的

**Comment by zhognsheng** [comment]
辛苦了,公司在等着用呢

**Comment by lihongxun945** [comment]
好的，我先定位下问题，不出意外的下一个版本会解决这个问题

**Comment by rockjava** [comment]
下一版什么时间发布？正在考虑使用这套ui

**Comment by lihongxun945** [comment]
下一个版本应该这周内会发布。

**Comment by 613660067** [comment]
同安卓手机遇到这个问题，等解决后使用！

**Comment by 613660067** [comment]
说明一下：用的乐视1S和魅蓝 进行的测试

**Comment by pinkdawn** [comment]
同样遇到了这个问题，等修复

**Comment by lihongxun945** [comment]
在 `dev` 分支上已经修复了这个问题了

**Comment by pinkdawn** [comment]
@lihongxun945 多谢！编译替换后，确认这个问题已经修复。

**Comment by lihongxun945** [comment]
V0.6.0 已经解决
