### ISSUE TITLE
rc1升级到正式版后$.showLoading()不居中

### ISSUE THREAD

**Issue by lottepie** [lihongxun945/jquery-weui#345]
升级了1.0正式版后，$.showLoading显示框往右下方移动了一下，导致不居中了。查看DOM发现，样式里有个transform:scale(1,1)，去掉这个就居中了。之前rc1下没有这个问题。

![qq 20170109092005](https://cloud.githubusercontent.com/assets/15645654/21755316/d95bc1bc-d64c-11e6-9de5-553aed0fe88b.png)
![qq 20170109092015](https://cloud.githubusercontent.com/assets/15645654/21755317/de199c2e-d64c-11e6-9173-483d88bc170f.png)

**Comment by lihongxun945** [comment]
不知道为什么你的代码是旧的，你可以查看线上的demo

**Comment by lottepie** [comment]
@lihongxun945 我是直接clone build分支，然后使用的是dist目录下的文件，文件都检查过了确实是最新的1.0.0

**Comment by lihongxun945** [comment]
@lottepie  那你看下线上的demo也是没有居中么

**Comment by lihongxun945** [comment]
最新的代码应该是 `transform: scale(1) translate(-50%, -50%)`

**Comment by lottepie** [comment]
代码确实是最新的，刚又用npm下了最新代码。奇怪的是表示的一瞬间貌似从中间位置突然跳到右下位置。代码什么都没动，就是早上升级到正式版后就出现这个问题，之前rc1时是正常的。

**Comment by lottepie** [comment]
貌似和什么库冲突了，导致样式被覆盖了，怀疑是SPA，把你的CSS中加上!important就好用了，暂时先这样用吧。
