### ISSUE TITLE
toast无法消失

### ISSUE THREAD

**Issue by stillyu** [lihongxun945/jquery-weui#347]
第一个toast还没关闭的时候就调用第二个toast，会出现toast无法自动消失的bug
运行环境：ios chrome
重现步骤：$.ajax 里的 brforeSend 和 succes 分别调用toast
错误代码：
$.ajax({
    type: "post",
    dataType: "json",
    url: url,
    data: data == null ? null : data,
    beforeSend: function () {
        $.showLoading();
    },
    success: function (res) {
        $.hideLoading();
        $.toast(res.message);
    },
    error: function (res) {
        $.hideLoading();
        $.toast(res.message, "forbidden");
    }
});

**Comment by hel2o** [comment]
请问你是怎么解决这个问题的？
