### ISSUE TITLE
允许自定义modal参数，设置是否自动关闭

### ISSUE THREAD

**Issue by bossware** [lihongxun945/jquery-weui#35]
对于自定义模态对话框的时候，有时候需要在按钮内校验表单数据是否完整，此时应该在用户提供的回调函数内自行决定是否关闭该对话框。

例如：
      el.click(function() {
        //先关闭对话框，再调用回调函数

        $.closeModal();

        if(buttons[i].onClick) {
          buttons[i].onClick();
        }
      });

代码修正为
      el.click(function() {
        //先关闭对话框，再调用回调函数
if(!params.config.customer_close) //当没有该配置或config.customer_close=true 的时候不主动关闭对话框；默认仍旧是主动关闭，只有配置了不主动关闭才不关闭
        $.closeModal();

        if(buttons[i].onClick) {
          buttons[i].onClick();
        }
      });

**Comment by lihongxun945** [comment]
这个建议非常好，我已经增加了一个 `autoClose` 的配置项，下一个版本会发布这个更新

**Comment by bossware** [comment]
我觉得这个关闭与自动关闭，以及允许多个对话框出现，可以参考artDialog的。我fork过去的分支也是加了autoClose配置项，但用的过程中，若出现了缺省的＄．ａｌｅｒｔ这样的默认调用，就会关掉所有的对话框，这不是期望的结果，关闭对话框的＄．ｃｌｏｓｅＭｏｄａｌ是否允许参数指定关闭哪个呢？ａｒｔＤｉａｌｏｇ是比较好的参考。

**Comment by lihongxun945** [comment]
其实我是认为需要同时弹出多个对话框本身就是不合理的，所以没有提供这种功能。

**Comment by bossware** [comment]
举个例子好了：
弹出第一个对话框是表单，对表单的验证的提示信息有两种方式，第一种是直接在第一个对话框里用增加元素位置并增加提示文字的方式进行（要求对话框能够自适应内容而自身大小进行调整）；第二种方式类似于alert原生函数的方式。但由于alert原生函数的方式无法指定其样式，所以如果能够有类似的替代方案自然就更好。所以这里的$.alert就成了一个比较好的选择。那么在Form dialog里弹$.alert提示用户也就顺理成章了。这个需求并不少见。当然是否合理，则不同人有不同看法。

**Comment by lihongxun945** [comment]
@bossware  对于手机这种小屏设备，弹窗之上再次弹窗的设计本身就是很不合理的。

**Comment by bossware** [comment]
@lihongxun945  嗯，只考虑手机的话不考虑多个层也是可以的。

**Comment by lihongxun945** [comment]
V0.6.0 已经 增加了一个配置，可以设置是否点击按钮自动关闭
