### ISSUE TITLE
使用 slider 后在微信页面导致页面无法上下滑动

### ISSUE THREAD

**Issue by libaolei168** [lihongxun945/jquery-weui#351]
# 提issue前请注意

- 错误代码：

 $('#slider').slider(function (per){
      console.log(per)
    })

- 运行环境：微信最新
- 重现步骤  调用这个slider 方法页面就无法上下滑动

- 期望结果：能上下滑动

自己修改了 看了下源码 ：t(document.body).on(t.touchEvents.move,t.proxy(this.touchMove,this)) 是给body绑定的  把document.body 修改为 this.container 就可以了

**Comment by lihongxun945** [comment]
感谢反馈，会在下一个版本修复。
绑定body 是为了在手指移动超出container范围依然可以操作滑块。
