### ISSUE TITLE
picker方法 setValue

### ISSUE THREAD

**Issue by xu-snow** [lihongxun945/jquery-weui#354]
`jQuery WeUI V1.0.0 
`
picker方法 setValue 需要先有open 方法之后才能生效

`$("#height").picker("setValue",["1","2","3"]) //无效果`
`
$("#height").picker("open");//添加，只需调用一次
`
`
$("#height").picker("close");//为了不显示而关闭
`
`
$("#height").picker("setValue",["1","2","3"]) //有效果
`

是否有更好的办法来调用setValue方法？

**Comment by lihongxun945** [comment]
暂时没有好的办法，因为open里面才会做一些初始化的操作。如果你必须要在初始化之后，open之前修改值，可以这样：
```
$('xxx').data('calendar').params.value[0] = '2012-12-12'
```
