### ISSUE TITLE
下拉刷新 bug

### ISSUE THREAD

**Issue by yupengcheng** [lihongxun945/jquery-weui#36]
下拉刷新功能有个小bug,当一个长页面已经往下浏览一定距离后,这时想往上滚动时就会触发下拉刷新,应该设置为只有当页面没有滚动为顶部位置时才触发下拉刷新

**Comment by lihongxun945** [comment]
你说的这个问题在官方demo上有么？

**Comment by Craft24** [comment]
我也遇到了，比较长的页面往下滑动一定距离，这时想返回顶部，结果触发刷新

**Comment by lihongxun945** [comment]
我看你的描述，感觉应该是滚动容器有问题，你可以部署下代码让我看看么，或者把方便的话把代码发给我看看

**Comment by ZongweiBai** [comment]
同样遇到这个问题，如果对div进行下拉操作就会出现，对于document.body下拉就没有这个问题。

jsp代码如下：
`<div id="infoContentDiv">
			
			<div class="weui-pull-to-refresh-layer">
		      <div class='pull-to-refresh-arrow'></div>
		      <div class='pull-to-refresh-preloader'></div>
		      <div class="down"> 下拉刷新</div>
		      <div class="up">释放刷新</div>
		      <div class="refresh">正在刷新</div>
		    </div>
		    
			<div class="adplay">
		       <div id="iSlider-wrapper"></div>
			</div>
			<div class="wzhaom">
				<ul id="infoListUl">
			        
			    </ul>
			</div>
		</div>`

js中调用：
`// 下拉刷新
	$("#infoContentDiv").pullToRefresh().on("pull-to-refresh", function() {
		hasNext = true;
		loadDocument("refresh");
	});`
