### ISSUE TITLE
weui.css报错

### ISSUE THREAD

**Issue by joriewong** [lihongxun945/jquery-weui#361]
![image](https://cloud.githubusercontent.com/assets/11408040/22921799/125a6ac2-f2d6-11e6-8ffb-30fd7e4fbd7b.png)

**Comment by joriewong** [comment]
![image](https://cloud.githubusercontent.com/assets/11408040/22921783/fecbcbb8-f2d5-11e6-93ba-c70c22a44bc5.png)

**Comment by sndwow** [comment]
这个错误应该是IDE检查HTML标签提示的，因为html标签到body标签缺少<head></head>，你尝试加上去看看

**Comment by joriewong** [comment]
这是npm install的源文件

**Comment by lihongxun945** [comment]
这是我下载官方weui的时候的一个bug，下一个版本会修正。你去weui那边下载即可
