### ISSUE TITLE
$.photoBrowser在页面初始化完成后，第一次调用$.photoBrowser.open(index),且index不为0时，显示出现问题

### ISSUE THREAD

**Issue by hihiwjc** [lihongxun945/jquery-weui#369]
$.photoBrowser在页面初始化完成后，第一次调用$.photoBrowser.open(index),且index不为0时，显示出现问题，可能是在swiper.js第3862行self.initParams();未调用成功

**Comment by huanghui8030** [comment]
请问这个问题有解决方案吗

**Comment by hihiwjc** [comment]
暂时没有解决

**Comment by huanghui8030** [comment]
我发现只要通过debug走流程就会显示正常，但是正常页面就有问题。

**Comment by huanghui8030** [comment]
已解决，只能修改源码，3867行里面重新执行下self.initParams();即可。
![image](https://user-images.githubusercontent.com/2831814/28263121-3c285084-6b18-11e7-84ad-76e082886cc4.png)
