### ISSUE TITLE
没有select组件组件吗？

### ISSUE THREAD

**Issue by alongSelf** [lihongxun945/jquery-weui#37]
尊敬的开源爱好者:
        您好!我有一个这样的场景。性别选择，有三个选项文本值分别是 男，女，保密。提交到后台的值为1,2,0。
        走了一所有的demo，后来发现只有只有picker最适用，但是只能得到这只文本值，不能设置要提交的值，可能是我不熟悉您的框架所有没有找到合适的组件，
        请您指点一下，万分感激。
                                                                                                                        alongSelf
                                                                                                               2016年4月1日

**Comment by Craft24** [comment]
这个不需要用什么特别的组件，直接用html代码好了
`<div class="weui_cell weui_cell_select">
<div class="weui_cell_bd weui_cell_primary">
<select class="weui_select" name="select1">
<option value="0" selected="">选择</option>
<option value="1">微信号</option>
<option value="2">QQ号</option>
<option value="3">Email</option>
</select>
</div>
</div>`

**Comment by lihongxun945** [comment]
其实这个组件已经在开发了，下一个版本就会有弹出的 单选和多选功能，你如果很急着要看的话，可以用dev分支的最新代码

**Comment by lihongxun945** [comment]
V0.6.0 已经解决
