### ISSUE TITLE
android4存在dialog点不动，官方的可以

### ISSUE THREAD

**Issue by ww380459000** [lihongxun945/jquery-weui#38]
android4存在dialog自带浏览器跟微信提供的都点不动，uc浏览器可以，官方的可以

**Comment by ww380459000** [comment]
应该是不支持css3

**Comment by lihongxun945** [comment]
官网demo可以点，你的不能点，那么你应该先找一下自己的原因

**Comment by ww380459000** [comment]
用的是这个框架，分析了下是应该是不支持css3，我那手机是小米1代，android4.1版本，uc上是好的，就系统自带的跟微信不行，官网是直接把display:none去掉了，jquery是用的css3的特性，jquery的demo也是不行的。

**Comment by ww380459000** [comment]
应该是weui_mask_visible，weui_dialog_visible这2个class导致

**Comment by lihongxun945** [comment]
@ww380459000  你说的官方是指 weui 而不是 jquery weui吗？

**Comment by lihongxun945** [comment]
我手头没有4.1 的机器可以测试，我先自己测试下，有问题的话我在联系你

**Comment by ww380459000** [comment]
官网指的是weui，都是用jquery weui提供的demo测试的，应该是重写weui_mask，weui_dialog这些导致的，还有包括dialog居中显示，可否这些样式使用weui的？

**Comment by lihongxun945** [comment]
明白了，我确实重写了部分weui的样式，weui的居中不够灵活我改变了居中方式。等我这几天先自己找机器测试一下

**Comment by lihongxun945** [comment]
我在一个安卓 4.0 的机器上重现出了 calendar 和 picker 不显示的bug，但是还是无法重现出 dialog 无法关闭的bug

**Comment by ww380459000** [comment]
难道就4.1有问题，4.2我测试也是好的。你是用微信里面打开的吗？

**Comment by lihongxun945** [comment]
@ww380459000  你试试最新版还有没有问题，上周刚发布的

**Comment by ww380459000** [comment]
dialog不行，calendar 和 picker的都OK了

**Comment by sy08400840** [comment]
@ww380459000 我今天也开始用了，刚开始dialog是不行，只能弹出但无法关闭，后来发现我没引入jquery-weui.css，一定要引入这两个<link rel="stylesheet" href="../lib/weui.min.css">，<link rel="stylesheet" href="../css/jquery-weui.css">，只引官方的weui.min.css就会只弹出不能关闭。然后另一个问题来了，就是居中的问题，改一下那个对话框样式就行了：
width: 85%;
top: 50%;
left: 50%;
transform: translate(-50%, -50%);
-ms-transform: translate(-50%, -50%);	/* IE 9 */
-moz-transform: translate(-50%, -50%);	/* Firefox */
-webkit-transform: translate(-50%, -50%); /* Safari 和 Chrome */
-o-transform: translate(-50%, -50%); 	/* Opera */

**Comment by lihongxun945** [comment]
CSS是一样要引入的，没有居中的问题只有在PC上页面很宽才会出现，在手机上不会出现的。下次我会修复这个问题。
