### ISSUE TITLE
在ios上$.alert会出现先从右下角弹出然后才居中的问题

### ISSUE THREAD

**Issue by fengqiming** [lihongxun945/jquery-weui#384]
- 错误代码：$.alert('conttent', 'title');
- 运行环境：ios10.1.1，WeChat6.5.5
- 重现步骤   
![default](https://cloud.githubusercontent.com/assets/20139501/24538820/fe7e9242-161d-11e7-9375-74c130338cc6.gif)
- 正确的结果应该是直接从中间弹出，而不是从右下角弹出再居中

详细情况：$.alert()对话框在ios上会发生错位情况，当调用时会从右下角弹出，然后才回到中间。就像图片所呈现的问题一样

**Comment by ladykillertao** [comment]
我用的toast 也是这种现象

**Comment by fengqiming** [comment]
@ladykillertao 现在解决了木有

**Comment by fengqiming** [comment]
@ladykillertao 你试一下这个方法，如果用cdn的话直接写在你自己的样式表里面覆盖掉
jquery-weui.css 文件的的 769 行处做如下修改即可：

.weui-dialog,
.weui-toast {
-webkit-transition-duration: .2s;
transition-duration: .2s;
opacity: 0;

/*修改前*/
/*-webkit-transform: scale(0.9) translate(-50%, -50%);
transform: scale(0.9) translate(-50%, -50%);*/
/*修改后*/
-webkit-transform: scale(1) translate(-50%, -50%);
transform: scale(1) translate(-50%, -50%);

-webkit-transform-origin: 0 0;
transform-origin: 0 0;
visibility: hidden;
margin: 0;
top: 45%;
z-index: 2000;
}

**Comment by 1213042026** [comment]
似乎可以了

**Comment by fengqiming** [comment]
@1213042026 是作者修复了么？

**Comment by ladykillertao** [comment]
@fengqiming 可以了 非常感谢

**Comment by fengqiming** [comment]
@ladykillertao 解决了就好，不用客气，我也是刚好看到这种方法，所以发现我的可以解决，然后发给你们看看能不能帮到你们o(∩_∩)o 哈哈

**Comment by setterzhang** [comment]
今天刚好也遇到,还好看的你的方法.希望作者早点解决这个问题

**Comment by fengqiming** [comment]
@setterzhang 哈哈，解决就好，如果作者修复的话就会变得方便好多啦

**Comment by lihongxun945** [comment]
感谢 @fengqiming  下一个版本会修复。

**Comment by cang9855** [comment]
-webkit-transform: scale(1) translate(-50%, -50%);
transform: scale(1) translate(-50%, -50%);****  修改后还是不行

**Comment by fengqiming** [comment]
@cang9855 加上important试试

**Comment by cang9855** [comment]
@fengqiming 页面审查元素，已经修改成功了，和加important 关系大吗？

**Comment by fengqiming** [comment]
@lihongxun945 感谢作者

**Comment by fengqiming** [comment]
@cang9855 important的优先级最高，修改后不行可能是你其它样式给覆盖了
