### ISSUE TITLE
苹果机打开日历控件，日期全变为NA了

### ISSUE THREAD

**Issue by lasthelloworld** [lihongxun945/jquery-weui#398]
# 提issue前请注意

微信：QQ浏览器X5内核

- 期望结果：
![screenshot_2017-05-11-21-53-07-471_com tencent mm](https://cloud.githubusercontent.com/assets/10508636/25954890/2ef922b0-369a-11e7-92f2-6cf389628602.png)

实际结果：

![screenshot_2017-05-11-21-54-05-205_com tencent mm](https://cloud.githubusercontent.com/assets/10508636/25956495/763fe628-369e-11e7-9d2a-75cb2977c86c.png)

不兼容IOS
测试地址：
http://huaruan.deyoukeji.cn/planlist?typeID=6页面中的，订房下单界面日期选择问题

**Comment by lasthelloworld** [comment]
希望作者给与一些指导，我这边调试没有报错呢，第一个图是安卓机子的，第二个图是苹果的

**Comment by lasthelloworld** [comment]
群里有同问题的人说：不设置默认时间和最小时间就不会有这个问题，回去试试

**Comment by wxuonline** [comment]
https://github.com/wxuonline/weui

**Comment by houzihua** [comment]
https://www.w3cways.com/2051.html  看看这个

**Comment by lasthelloworld** [comment]
https://github.com/wxuonline/weui
@wxuonline  大概描述的是IOS日期格式问题，但是下载你更新后的jquery weui.js后，
1.初始化日历控件时，年份为NAN，
2.切换年或月，日期均变为了NAN
请问，在什么时候需要格式转换把-替换为/

**Comment by lihongxun945** [comment]
确实是由于 ios上不支持 `-` 作为日期分隔符导致的， `v1.1.2` 版本会修复。
