### ISSUE TITLE
loading不居中的问题

### ISSUE THREAD

**Issue by RunningCoderLee** [lihongxun945/jquery-weui#4]
由于.weui_toast的margin-left属性采用的单位是rem，而.weui_toast的width属性采用的是em单位，因此在html和body的font-size属性值不一样时，会导致.weui_toast的margin-left：-3,8rem实际上并不是.weui_toast的width：7.6em的一半, 因此会出现不居中的情况。

**Comment by lihongxun945** [comment]
V0.5.0 已经修复这个问题
