### ISSUE TITLE
update to WEUI V1.1.2

### ISSUE THREAD

**Issue by lihongxun945** [lihongxun945/jquery-weui#400]
Will update to WEUI V1.1.2, changelog https://github.com/weui/weui/blob/master/CHANGELOG.md
Most important change will be:
- new swipe to delete component.

**Comment by acid122** [comment]
很期待楼主跟新左滑删除功能，请问近期会更新到WEUI V1.1.2吗，谢谢 @lihongxun945

**Comment by lihongxun945** [comment]
Done
