### ISSUE TITLE
v1.0.1 toast出现未居中

### ISSUE THREAD

**Issue by 2FA0** [lihongxun945/jquery-weui#402]
![image](https://cloud.githubusercontent.com/assets/11802492/26432549/0f69561e-412f-11e7-88bd-58a701bc92e7.png)

上图是在pc chrome 上的模拟图，在iphone上的测试还是出现一样的情况（先居中一下（不到一秒），随即变成上图的模样）
chrome版本58.0.3029.96
ios版本10.3.1
微信版本：6.5.7

**Comment by houzihua** [comment]
检查下是不是自己写的什么地方样式影响了。。。

**Comment by wishflyer** [comment]
这个问题，之前有人给出了办法了：

        /*修正jquery-weui对话框在IOS上的弹出起始位置的问题*/
        .weui-dialog,
        .weui-toast {
            -webkit-transition-duration: .2s;
            transition-duration: .2s;
            opacity: 0;
            -webkit-transform: scale(1) translate(-50%, -50%);
            transform: scale(1) translate(-50%, -50%);
            -webkit-transform-origin: 0 0;
            transform-origin: 0 0;
            visibility: hidden;
            margin: 0;
            top: 45%;
            z-index: 2000;
        }
