### ISSUE TITLE
Calendar控件

### ISSUE THREAD

**Issue by dwbweibo** [lihongxun945/jquery-weui#41]
在PC chrome浏览器上发现日期弹不出来,当屏幕小于768时日期控件可以弹出

**Comment by dwbweibo** [comment]
非device mode模式时会有这个问题 错误问题: Uncaught TypeError: $.popover is not a function    jquery-weui.js:2666

**Comment by lihongxun945** [comment]
我知道是什么问题了，感谢反馈，我会在下一个版本修正的。
不过jquery weui本身是针对微信的，在微信中是不会出现你说的问题的，所以你可以放心使用。

**Comment by ww380459000** [comment]
年份区间可否加个配置？

**Comment by lihongxun945** [comment]
V0.6.1 已经修复无法弹出的bug
