### ISSUE TITLE
某些情况下遮罩层挡住了modal对话框层

### ISSUE THREAD

**Issue by bossware** [lihongxun945/jquery-weui#42]
某些情况下，遮罩层挡住了modal对话框层，导致无法点击对话框按钮等操作；通过修正遮罩层的z-index:3得到了

解决建议css中遮罩层调低 z-index 到3，或 比modal的层更低一些

**Comment by lihongxun945** [comment]
@bossware 这个是 `weui.min.css` 压缩的时候改变了`z-index` 导致的，你可以试一下最新的版本，已经解决了这个问题
