### ISSUE TITLE
下拉刷新中当滚动条不在顶端时，这时下拉刷新功能也会启用，导致滚动条无法拉到顶部

### ISSUE THREAD

**Issue by suyana** [lihongxun945/jquery-weui#422]
下拉刷新中当滚动条不在顶端时，这时下拉刷新功能也会启用，导致滚动条无法拉到顶部
无法再次下拉刷新

**Comment by suyana** [comment]
经测试是发现滚动条存在上层容器而非当前容器,导致 
PTR.prototype.touchMove= function(e) {
     .....
     if(this.container.scrollTop() > 0) return; //导致此行永远不执行导致

经过更改,为方法新增一个变量,用于传入父容器的对象(添加见备注)
var pullToRefresh = function(el,scrollTopEl) {//suyana add scrollTopEl
    new PTR(el,scrollTopEl);//suyana add scrollTopEl
  };
  var pullToRefreshDone = function(el) {
    $(el).removeClass("refreshing");
  }
  $.fn.pullToRefresh = function(scrollTopEl) {//suyana add scrollTopEl
    return this.each(function() {
      pullToRefresh(this,scrollTopEl);//suyana add scrollTopEl
    });
  }
  var PTR = function(el,scrollTopEl) {//suyana add scrollTopEl
    this.container = $(el);
    this.distance = 50;
    this.attachEvents();
    this.elParent=scrollTopEl;//suyana add this row
  }


  PTR.prototype.touchMove= function(e) {
    .......
    if(this.container.scrollTop() > 0) return;    
    if(this.elParent.scrollTop()>0)return;//suyana add this row
    ......

=========================================================
以上,问题解决,建议作者增加个参数(如果为空取注册下拉的容器)来应对此情况.
感谢作者的辛勤付出.ths

**Comment by lengziyu** [comment]
```
PTR.prototype.touchMove= function(e) {
.......
if(this.container.scrollTop() > 0) return;
if(this.elParent.scrollTop()>0)return;//suyana add this row
......
```
@suyana  `scrollTop` Cannot read property 'scrollTop' of undefined

**Comment by lengziyu** [comment]
我直接改为
`if($('html').scrollTop() > 0) return;`解决了，发现只检测html的滚动位置，其他全是0

**Comment by AyoDosahard** [comment]
大神 有修改过的源码吗？

**Comment by ikkong** [comment]
@lengziyu if($('html').scrollTop() > 0) return; 不适用于所有情况，还是加个参数比较好

**Comment by lihongxun945** [comment]
这种情况都是由于在错误的容器上初始化导致的。请注意你初始化的容易必须是真正发生滚动的元素。

**Comment by CyrusWU-APJ** [comment]
var ptr = $('#pullrefresh').data('ptr');
		var prtTouchMoveEvent = ptr.touchMove;
		ptr.container.on($.touchEvents.move, $.proxy(function(){
			if($('真正滚动的元素').scrollTop() > 0) return;
			prtTouchMoveEvent.call(ptr, e);
		}, ptr));

不影响其他页面的
