### ISSUE TITLE
日期时间不可以只选择年月

### ISSUE THREAD

**Issue by amangqq** [lihongxun945/jquery-weui#423]
我看了，并没有参数可以选择，我只想要年月

**Comment by wakerman** [comment]
自己生成

**Comment by caoshuaitong** [comment]
有没有解决

**Comment by lihongxun945** [comment]
只要年月，用picker 传入数据就行了

**Comment by coderkw** [comment]
如果要做成可以选择年月，用picker传入的值不可改变，不能根据年份来判定可选月份（比如现在是2019年6月，那么只当选择19年时，月份最大只能选择到6月份，而选18年，则可以选择到12月了）不能像地址一般做到联动效果
