### ISSUE TITLE
Toast loading会先出现在左下角闪动一下后再居中

### ISSUE THREAD

**Issue by dreling8** [lihongxun945/jquery-weui#428]
- 错误代码：无
- 运行环境：系统版本IOS10.3.3 ，微信版本6.5.12
- 重现步骤：进入页面js调  $.showLoading()，动态加载数据时会先出现在右下角再回到居中位置
- 期望结果，实际结果（最好有截图）

**Comment by dreling8** [comment]
weui自带的toast不会出现这个问题

**Comment by guitarist0207** [comment]
问题列表里有人遇到了类似问题，提供了解决方案，可以查一下

**Comment by ihuangmx** [comment]
能否告知是解决方案在那个 issue 呢

**Comment by jerrygaoc** [comment]
之前提过这个Issue 解决方案在这里https://github.com/lihongxun945/jquery-weui/issues/420,
