### ISSUE TITLE
建议改进datetimePicker的体验效果

### ISSUE THREAD

**Issue by siriusbean** [lihongxun945/jquery-weui#429]
$("#getTime").datetimePicker({
        title: '选择日期',
        yearSplit: '年',
        monthSplit: '月',
        dateSplit: '日',
        min: "2017-08-19",
        max: "2017-09-29",
        times: function () {
          return [  // 自定义的时间
            {
              values: (function () {
                var hours = [];
                for (var i=0; i<24; i++) hours.push(i > 9 ? i : '0'+i);
                return hours;
              })()
            },
            {
              divider: true,  // 这是一个分隔符
              content: '时'
            },
            {
              values: (function () {
                var minutes = ['00', '10', '20', '30', '40', '50'];
                //var minutes = [];
                //for (var i=0; i<59; i++) minutes.push(i > 9 ? i : '0'+i);
                return minutes;
              })()
            },
            {
              divider: true,  // 这是一个分隔符
              content: '分'
            }
          ];
        },
        onChange: function (picker, values, displayValues) {
        	console.log("values=="+values);
        	console.log("getTime=="+$("#getTime").val());
        	var date = values[0]+"-"+values[1]+"-"+values[2];
        	var week = getMyDay(new Date(date));
        	var min = week+" "+values[3]+":"+values[4];
        	$("#getDate").html(date);
        	$("#getMin").html(min);
        	
        	//同步设置还车时间，加2天时间
        	var StartTime = values[0]+"-"+values[1]+"-"+values[2]+" "+values[3]+":"+values[4];
        	var StartTime2 = new Date(StartTime);
        	setReturnTime(addDate(StartTime2,2));
          	
        }
      });

![image](https://user-images.githubusercontent.com/31140481/29471988-bd43a0b2-8484-11e7-8ca4-de323ded79a1.png)
如图所示，限制时间段为“min: "2017-08-19"-"2017-09-29"，但是年份和月份还是显示所有的，这让用户的体验变得不好，因为用户会觉得既然显示了，那应该可以选择，但实际上的选择了不的。建议不显示时间范围段以外的年份和月份。

**Comment by lihongxun945** [comment]
感谢建议，下一个版本将可以配置默认的 years 和 monthes

**Comment by lihongxun945** [comment]
v1.1.2
