### ISSUE TITLE
picker的一个小bug

### ISSUE THREAD

**Issue by MyLittleStone** [lihongxun945/jquery-weui#432]
【问题描述】
当用选择器选择的是多个而并非一个对象的时候，picker出错了。如：
$("#SP_Self_Detail_Start,#SP_Self_Detail_End").picker(...);
此时单击SP_Self_Detail_End依然显示的是SP_Self_Detail_Start的值，而并非是SP_Self_Detail_End的值。
【问题所在代码】
$.fn.picker = function(params) {
    var args = arguments;
    return this.each(function() {
      if(!this) return;
      var $this = $(this);
      var picker = $this.data("picker");
      if(!picker) {
        params = params || {};//这里应该新建变量不应该是直接覆盖参数。
        var inputValue = $this.val();
        if(params.value === undefined && inputValue !== "") {
          params.value = (params.cols && params.cols.length > 1) ? inputValue.split(" ") : [inputValue];
        }
        var p = $.extend({input: this}, params);
        picker = new Picker(p);
        $this.data("picker", picker);
      }
      if(typeof params === typeof "a") {
        picker[params].apply(picker, Array.prototype.slice.call(args, 1));
      }
    });
  };
【问题修复】
$.fn.picker = function (params) {
		var args = arguments;
		return this.each(function () {
			if (!this) return;
			var $this = $(this);
			var picker = $this.data("picker");
			if (!picker) {
				var p = $.extend(true, { input: this }, params || {});//这里不用参数而是新建变量
				var inputValue = $this.val();
				if (p.value === undefined && inputValue !== "") {
					p.value = p.cols.length > 1 ? inputValue.split(" ") : [inputValue];
				}
				picker = new Picker(p);
				$this.data("picker", picker);
			}
			if (typeof params === typeof "a") {
				picker[params].apply(picker, Array.prototype.slice.call(args, 1));
			}
		});
	};

**Comment by lihongxun945** [comment]
已采纳，感谢您的建议
