### ISSUE TITLE
下拉刷新问题

### ISSUE THREAD

**Issue by 6gunner** [lihongxun945/jquery-weui#434]
# 下拉刷新没有判断当前容器是否本身可以滚动。

- 如果当前div的父容器设置overflow：scroll。页面上滑到底部后，无法向下滑动。会认为触发了下拉刷新事件、
- 错误代码:![image](https://user-images.githubusercontent.com/7445659/29767610-b065e89e-8c15-11e7-8d15-fa4a9910f0cd.png)

https://jsfiddle.net/gunner6/u3nkygsy/4/

**Comment by AyoDosahard** [comment]
请问 解决了吗？我也碰到了这个问题  求解决

**Comment by fashioncoolwan** [comment]
`<div id="mainDataTabs" style="height:100%; overflow:auto; display:none;">
        <div class="weui-pull-to-refresh__layer">
          <div class='weui-pull-to-refresh__arrow'></div>
          <div class='weui-pull-to-refresh__preloader'></div>
          <div class="down">下拉刷新</div>
          <div class="up">释放刷新</div>
          <div class="refresh">正在刷新</div>
        </div>
        <div  id="pageApp" class="weui-cells" style="margin-top:0px;">
            <div class="weui-cell" v-for="(row,index) in rows">
                <div class="weui-cell__bd">
                    <a :href="#" style="display:block;">{{row.Title}}</a>
                    <span class="sub_title">{{row.Name}}</span>
                    <img v-if="row.Located" src="/images/pos.png" style="height:14px;" />
                </div>
                <div v-on:click="infoPanel(index)" class="weui-cell__ft">
                    <img src="/images/item_info.png" style="width:32px;" />
                </div>
            </div>
        </div>
    </div>`
`//下拉刷新
            $("#mainDataTabs").pullToRefresh().on("pull-to-refresh", function () {
                //查询数据
            });`
我这样是没问题的，之前也遇到过和你同样的问题，不过那时候的情况是pull-to-refresh事件是绑定在body上的，然后就发现pageApp列表只能往上滚动，往下滚动不了，后来改成把pull-to-refresh事件绑定在mainDataTabs上就没有问题了。

**Comment by lihongxun945** [comment]
碰到这种问题都是由于绑定错了容器导致的。你必须绑定在发生滚动的容器上，而不是随便绑定。
