### ISSUE TITLE
cdn问题

### ISSUE THREAD

**Issue by gianttt97** [lihongxun945/jquery-weui#452]
<script src="//cdn.bootcss.com/jquery-weui/1.0.1/js/jquery-weui.min.js"></script>
这个cdn是不是出问题了

**Comment by jimrueaster** [comment]
bootcdn已经全面改用https了, 参见 《拒绝流量劫持，全面使用 HTTPS！》 http://blog.bootcdn.cn/only-https/ 

http://jqweui.com/download 也应该更新一下

**Comment by lihongxun945** [comment]
感谢 已更新
