### ISSUE TITLE
jquery-weui和微信的weui的冲突

### ISSUE THREAD

**Issue by CharlesJu1** [lihongxun945/jquery-weui#456]
jquery-weui很好。但使用过程中发现jquery-weui重新定义了weui里的一些样式。例如weui-dialog.　如果是作为扩展, jquery-weui不应该重定义weui中有的东西。如果不是扩展，这样的冲突带来一些问题。毕竟微信官方提供的weui中有的组件还是首选。

**Comment by fengqiming** [comment]
你可以试一下微信官方的weui.js，jquery-weui是改了一点点

**Comment by lihongxun945** [comment]
这不叫冲突，覆盖少量CSS本来就是很正常的
