### ISSUE TITLE
select扩展，如果在多选的默认值时候，会提示没有选择，这个BUG需要修复下

### ISSUE THREAD

**Issue by kong-qi** [lihongxun945/jquery-weui#459]
Select.prototype._bind = function(dialog) {
    var self = this,
        config = this.config;
    dialog.on("change", function(e) {
      var checked = dialog.find("input:checked");
      var values = checked.map(function() {
        return $(this).val();
      });
      var titles = checked.map(function() {
        return $(this).data("title");
      });
      self.updateInputValue(values, titles);

      if(config.autoClose && !config.multi) self.close();
    }).trigger('change')
    .on("click", ".close-select", function() {
      self.close();
    });
  }
因为已经有默认值了。但是提示没有选择多个，这个时候需要默认来一个自己选择，这样就不会出现没有选择了。
增加一个触发条件.trigger('change')

**Comment by itgallop** [comment]
select扩展在items长度为0时，点击input控件出错。
Uncaught TypeError: this.tpl is not a function
