### ISSUE TITLE
怎么主动触发下拉刷新事件

### ISSUE THREAD

**Issue by sprogjavasprog** [lihongxun945/jquery-weui#463]
您好！
我想在页面加载时自动触发一次下拉刷新事件，而不是当我去手动下拉时触发，请问要怎么处理
 
 $("#weuiDiv").pullToRefresh().on("pull-to-refresh", function () {
                        if (freshFlag) return;
                        pageNo = 1;
                        freshFlag = true;
                        EventHandler.search();
                    });

**Comment by lihongxun945** [comment]
v1.1.2 提供了相应的方法可以触发
