### ISSUE TITLE
#dialog 在iOS11.1.2中遇到的问题

### ISSUE THREAD

**Issue by phantom0309l** [lihongxun945/jquery-weui#464]
运行环境：iOS 11.1.2，微信6.5.22
在微信浏览器浏览 jqweui.com/dist/demos/dialog.html 
显示和隐藏时，会出现闪烁的情况；安卓则没有问题。

**Comment by lihongxun945** [comment]
重复 #384

**Comment by phantom0309l** [comment]
我的现象跟#384不一样，窗口+遮罩先是在中心弹出，然后又消失，又显示，消失的时候也是；
因为速度太快，我拍了视频转成gif就没法看出来了。
