### ISSUE TITLE
Calendar控件在safari下显示NaN

### ISSUE THREAD

**Issue by stillyu** [lihongxun945/jquery-weui#47]
chrome上没问题,safari上就显示NaN,不知是否个例

**Comment by includeleec** [comment]
这个bug几时能够解决啊？

**Comment by ww380459000** [comment]
http://stackoverflow.com/questions/4310953/invalid-date-in-safari
new Date(formatValue(values, displayValues).replace(/-/g, "/")).getTime()

**Comment by lihongxun945** [comment]
现在可以通过初始化的时候指定 `value`来解决，下一个版本会修复这个bug

**Comment by lihongxun945** [comment]
`V0.7.1` 已经修复此问题
