### ISSUE TITLE
福州91小工匠

### ISSUE THREAD

**Issue by VIPArcher** [lihongxun945/jquery-weui#482]
公众号：91小工匠
仅有前端demo页可以看这里：http://viparcher.gitee.io/xiaogongjiang/index.html
![236e7543aadca36e77ccd6a75d50e5ce](https://user-images.githubusercontent.com/9428090/34354230-d74780e8-ea67-11e7-97e1-6753d0234995.jpg)

<s>头一次用WEUI，可能写的不是很好。</s>

**Comment by 15011388106** [comment]
你这个是动态添加的元素吗，我的动态添加元素初始化 $('.weui-cell_swiped').swipeout() ;这个 都不管用
