### ISSUE TITLE
一个关于swiper的建议

### ISSUE THREAD

**Issue by icepole-jon** [lihongxun945/jquery-weui#49]
感谢作者的开源共享，这个项目帮助了我很多
一个小建议就是能不能把swipr的css剥离出来，因为对于那些使用别的swipe插件的人来说是有可能造成冲突的，我就使用了一个轻量级的swipe组件[swipe](https://github.com/lyfeyaj/swipe)只有18k，每次都要进行剥离。
当然只是一个建议 :)

**Comment by dd1994** [comment]
看了下 dist 目录下的 swiper.min.js ，居然有 75k, 这在移动端根本不能用

**Comment by lihongxun945** [comment]
@dd1994  因为比较大才独立出来。也没有你说的不能用那么夸张，服务器gzip之后其实只有20+K，跟一个大一点图片差不多

**Comment by lihongxun945** [comment]
@icepole-jon  我在最新版里面，其实 photos 中就实现了一个轻量的 swiper，也许我会考虑把它独立成一个组件

**Comment by dd1994** [comment]
@icepole-jon 现在 https://github.com/lihongxun945/jquery-weui/blob/master/src/js/photos.js 这个图片浏览器已经没有依赖 swiper 的了？

**Comment by lihongxun945** [comment]
是的，新版中的已经没有对swiper的依赖了，photobrowser自己实现了滑动操作

**Comment by dd1994** [comment]
因为最近在一个项目里只要用到这个图片浏览器，我做了一些改进

* 已经 CSS 剥离出来了，js 也剥离出来了, 把最新版的重构了一下(没有 swiper 依赖，也不要那个 jquery-extend.js), 去掉了 template7，换了个模板引擎
* 加入了双击放大，再次双击复原（跟朋友圈效果一致)
* 加入了 pb.open()支持一个 index 参数
* 修复了很多细节（比如只有一张图片时下面的小圆点不显示，还有一些样式细节尽量跟朋友圈一致）
* 修复了一些 bug，比如一些安卓机器滑动过快时下面的小圆点不切换，还有图片两侧那条奇怪的白线等等...
