### ISSUE TITLE
日期时间选择器无法设置最大最小值

### ISSUE THREAD

**Issue by ywss** [lihongxun945/jquery-weui#51]
$("#date").datetimePicker({
              title:"预定日期",
              minDate: "2016-03-03",
              maxDate: "2026-03-03"
          });

这么设置无效果啊，试了好几种组合，比如把 Date 去掉也不行，官方文档也有点排版问题

**Comment by lihongxun945** [comment]
用 `min` 和 `max` 来设置，你看看是不是你的版本不是最新版

**Comment by ywss** [comment]
试了下，还是不行。用的是demo里的页面
      $("#time").datetimePicker({
		  title: "预定日期",
			   min: "2016-03-03",
			   max: "2026-03-03"
		  }
	  );

**Comment by ywss** [comment]
好吧，我理解错了，原来这个是设置不能滚动到 min 和 max，我还以为是显示的在 min 和 max 之间呢，不知是否可以设置显示范围？

**Comment by lihongxun945** [comment]
设置显示范围其实也会有问题，你可以想一想，假设设置了 "2016-03-03" ，那么你在月份 02 到 03 滚动的时候，后面就会闪，非常奇怪

**Comment by ywss** [comment]
恩，我现在自己加了两个参数，只设置年的“显示”范围，配合 min 和 max ，月份啥的就只需要不能滚动就行了
var initYears = (function () {
          var arr = [];
          var min = 1970;
          var max = 2030;

          if (params.minY) min = params.minY;
          if (params.maxY)  max = params.maxY;

          for (var i = min; i <= max; i++) { arr.push(i); }
            return arr;
      })();
