### ISSUE TITLE
select 组件如何进行异步数据加载后显示..

### ISSUE THREAD

**Issue by weuitest888** [lihongxun945/jquery-weui#53]

**Comment by lihongxun945** [comment]
目前只能在你异步加载完了之后再初始化

**Comment by weuitest888** [comment]
已修改了，在你写的input click事件中，我添加了一个异步的配置，如果使用异步进行回调后执行弹出.
if(config.dataloadtype=="remote")
       {
          //alert("remotedata");
          config.loadremotedata(opennewremotedialog);
          return;
       }      
       opennewremotedialog(config.items);

loadremotedata 这个暴露在空间select中就可以了，还是多谢！！

$("#Text2").select({
               title: "选择职业",
               dataloadtype: "remote",
               loadremotedata: function (opendialog) {
} 
前台异步执行回调。
