### ISSUE TITLE
不支持移动端的webview啊

### ISSUE THREAD

**Issue by xylangyan** [lihongxun945/jquery-weui#54]
移动端的事件和web是不一样的，比如web是 click事件，而移动端是tap事件类似

**Comment by lihongxun945** [comment]
你是说手机和PC的区别吧？现在安卓和iOS都是支持click事件的，只不过ios上原生的click有延迟而已。click 的延迟问题你可以通过 fastclick 解决。如果有具体组件的bug，你可以单独提出来

**Comment by xylangyan** [comment]
恩，这个好办，唉还有个问题想请教下，weui中的好多单位用的是em  而现在h5开发大多数都要用 rem作为单位。em在手机上得兼容性好像不是很好。
还有就是如果用了backbone，在jquery-weui 中是获取不到 document对象的，所以在$(document).on 这种绑定的事件不起作用，有什么办法解决么

**Comment by xylangyan** [comment]
我看错了，可以获取。

**Comment by lihongxun945** [comment]
`em` 和 `rem` 倒不是兼容性问题，是因为 weui 官方用的就是 `em`，我不想改动官方的CSS
