### ISSUE TITLE
dialog 在大于1024宽度时不居中

### ISSUE THREAD

**Issue by lgh06** [lihongxun945/jquery-weui#56]
http://lihongxun945.github.io/jquery-weui/dist/demos/dialog.html 点开一个按钮 可复现。
建议在jquery-weui.css中，像官方css一样，对left定位设置媒体查询。

**Comment by sy08400840** [comment]
@lgh06 你说的是电脑浏览器吧，我用电脑浏览器是这样，但是1080p的手机没问题，没有2K屏，不知道2K啥样，应该没事

**Comment by lihongxun945** [comment]
1024px 以上宽度会出现，下一个版本修复。

**Comment by lihongxun945** [comment]
V0.6.1 已经修复
