### ISSUE TITLE
官网cdn源失效

### ISSUE THREAD

**Issue by socalledPF** [lihongxun945/jquery-weui#587]
官网cdn源失效

**Comment by lijun1243939149** [comment]
你们也用的 bootcss 的么。。。我们公司一大早，所有服务全崩了。。。 bootcss迁移了。。。

**Comment by gujinzhi** [comment]
早上我才点关注，才多久就崩溃了。。。我好害怕。

**Comment by lijun1243939149** [comment]
![image](https://user-images.githubusercontent.com/13789967/54817481-0ad3b300-4cd2-11e9-8bde-7c51e5b32fc9.png)
