### ISSUE TITLE
popup某种情况下无法遮罩

### ISSUE THREAD

**Issue by arange** [lihongxun945/jquery-weui#59]
问题描述：popup弹出的遮罩层被页面内容挡住
解决办法：将weui-popup-container的position属性由fixed改为static之后一切正常
问题原因：未知，未深究。

**Comment by arange** [comment]
另外，这种情况下，假如原页面长度超出屏幕高度，popup还可以向上滑动并露出下面的页面内容。不知道这个是不是bug？还是因为修改了position的缘故？

**Comment by lihongxun945** [comment]
我猜测是不是你的页面结构有问题，或者是某些手机的兼容性问题。你描述的问题可以用官网的demo复现出来么。

**Comment by arange** [comment]
找到原因了，z-index不够
原来的z-index:100是加在weui-popup-modal上的，改为加在weui-popup-container上后就正常了。
不需要修改position属性，修改了会导致一系列bug。

**Comment by arange** [comment]
另外，如果修改z-index属性，其他z-index:100的控件也可能被遮盖，比如picker
