### ISSUE TITLE
a标签关闭popup在移动设备上不生效的解决方法

### ISSUE THREAD

**Issue by arange** [lihongxun945/jquery-weui#60]
问题描述：给a标签设置class属性为close-popup时，如果不设置href属性（哪怕是href="#")，并且没有其他js事件监听该标签，在移动设备上会导致按钮事件不触发。
建议：在描述中写明。

ps:这个应该是通用问题？

**Comment by lihongxun945** [comment]
给 A 标签设置 href 属性应该是默认的标准了
