### ISSUE TITLE
关于timepicker

### ISSUE THREAD

**Issue by diorslau** [lihongxun945/jquery-weui#62]
希望timepicker也加一个配置选项,能提供只选择日期或者时间的.

**Comment by sy08400840** [comment]
恩，这个应该有，很多情况不需要选择时和分，只需要年月日就够了

**Comment by lihongxun945** [comment]
只提供日期的有专门的日历组件！ 只提供时间的目前确实还没有，但是用picker实现起来其实非常简单。

**Comment by sy08400840** [comment]
哦，对= =
