### ISSUE TITLE
地址选择器假死问题

### ISSUE THREAD

**Issue by stillyu** [lihongxun945/jquery-weui#63]
地址选择器,如果多次切换"省份",中间的市"会"变得无法滑动,右边的"区"可以正常滑动

**Comment by lihongxun945** [comment]
描述下你的具体系统型号，和用的浏览器版本

**Comment by stillyu** [comment]
ios9.3和chrome49都会有这个问题,我晚些时候再测试下是否个例

**Comment by Stanlie29** [comment]
原因是你使用了1.x的jquery，用2.x就沒有問題了
