### ISSUE TITLE
日历组件不能使用，点击报错 

### ISSUE THREAD

**Issue by jston** [lihongxun945/jquery-weui#64]
报错信息:$.popover is not a function
官方的demo也是同样的错误，谷歌浏览器

**Comment by includeleec** [comment]
测试的时候，浏览器不要超过760px

**Comment by sy08400840** [comment]
把电脑浏览器调窄就可以用了。不过日历组件貌似在点击左右箭头无论是月份还是年份时，页面自动滚回顶部，而直接点击日期就没问题

**Comment by lihongxun945** [comment]
重复了 https://github.com/lihongxun945/jquery-weui/issues/41
