### ISSUE TITLE
Calendar组件点击月份或年份的左右箭头，页面会自动回滚到顶部

### ISSUE THREAD

**Issue by sy08400840** [lihongxun945/jquery-weui#65]
电脑和微信浏览器都发现如果页面内容长，日历在最下部，调出组件后点击月份或年份的左右箭头，页面会自动回滚到顶部，选择day后页面依然处于最顶部；如果调出组件后直接选择day就不会回滚。

**Comment by lihongxun945** [comment]
这个确实是一个bug，我会在下一个小版本修复。原因是因为年月的 A 标签用的是 `href='#'` ，你也可以修改模板来修复这个问题。

**Comment by lihongxun945** [comment]
V0.6.1 已经修复这个问题
