### ISSUE TITLE
Calendar组件点击灰色day会出现重叠问题

### ISSUE THREAD

**Issue by sy08400840** [lihongxun945/jquery-weui#66]
![default](https://cloud.githubusercontent.com/assets/18552473/14661819/5f82390e-06e3-11e6-8607-46391972f7e6.JPG)
![2](https://cloud.githubusercontent.com/assets/18552473/14662252/04a41d32-06e7-11e6-87fa-74b20f4c341d.jpg)

如图，调出组件后是可以通过左右滑动day区域来翻月的，如果点击了灰色day，就不能再翻月了，只能通过选择月份的左右箭头了，然后问题来了，左右点着点着某些月份就会出现day叠加的情况。只有一旦选择灰色day会出现这种情况，选择黑色就没有问题。怎么破？或者把灰色day设为不可选择也可以。

**Comment by lihongxun945** [comment]
你先试下在官网的示例上进行这个操作能重新出bug么

**Comment by sy08400840** [comment]
@lihongxun945 jquery-weui-build\dist\demos里面的calendar.html也有这个问题，就是一旦选择灰色day以后，首先是不能通过滑动day区域来翻月份，然后是多点击几次选择月份的左箭头，再点几次右箭头，就会发现重叠情况。只点击一次左箭头和一次右箭头是没有的，只有连续点击左，再连续点击右才有。
![ad2e tmp](https://cloud.githubusercontent.com/assets/18552473/14662650/f0452350-06ea-11e6-92fb-e43939630c16.jpg)

**Comment by lihongxun945** [comment]
我找到原因了，我今天会发布一个小版本修复这个问题。

**Comment by lihongxun945** [comment]
V0.6.1 已经修复这个问题，你可以用最新版测试一下
