### ISSUE TITLE
日历组件怎么手动打开和关闭？

### ISSUE THREAD

**Issue by jston** [lihongxun945/jquery-weui#70]

**Comment by lihongxun945** [comment]
你可以通过 `$("input").trigger("click")` 来手动打开，通过 `$.closePicker()` 来关闭，因为其实calendar和picker用的是同一个弹出方式。

**Comment by lihongxun945** [comment]
这样确实不是很方便，API 不太统一，下次我增加 `open` 和 `close` 方法

**Comment by lihongxun945** [comment]
`V0.7.1`版本开始，可以通过 `$().calendar("open")`, `$().calendar("close")` 打开和关闭
