### ISSUE TITLE
日期选择器，IOS上不设value，出现NaN

### ISSUE THREAD

**Issue by tomoyuen** [lihongxun945/jquery-weui#71]
[见截图](http://7xian5.com1.z0.glb.clouddn.com/665989524158431832.jpg)

**Comment by tomoyuen** [comment]
已找到问题，是在默认显示今天的时候，月份和时间没有补全两位导致
`params.value = [today.getFullYear() + "-" + (today.getMonth() + 1) + "-" + today.getDate()]`

**Comment by sy08400840** [comment]
对，有这个问题。今天用同事的苹果4S就看到所有的日期全是nan

**Comment by lihongxun945** [comment]
已经在 dev 分支上修复了这个问题，下一次发布新版本的时候就好了

**Comment by tomoyuen** [comment]
OK

**Comment by lihongxun945** [comment]
在新版本发布之前，暂时可以通过在JS初始化的时候指定 `value` 来解决

**Comment by lihongxun945** [comment]
上线之后再关闭这个问题

**Comment by 7PLonG** [comment]
“JS初始化的时候指定 value ”,
重复选择当前日期无反应，不触发任何事件。只能救急

**Comment by lihongxun945** [comment]
`V0.7.1` 已经解决这个问题
