### ISSUE TITLE
栅格在低端平板和华为手机上有兼容性问题

### ISSUE THREAD

**Issue by anley360106** [lihongxun945/jquery-weui#73]
.weui-row的栅格系统在低端平板和华为手机上有兼容性问题，微信客户端为最新。
.weui-col-25项之间没有间距，项数量超过4个后不会换行，横着一排撑破.weui-row元素

**Comment by lihongxun945** [comment]
我手头没有华为的收集，你的手机系统版本是多少？另外weui已经全量升级了blink内核，你看看升级之后还有问题么。
