### ISSUE TITLE
select 选的值跟上次相同时不能自动关闭

### ISSUE THREAD

**Issue by ZivZhao** [lihongxun945/jquery-weui#74]
select组件选定的值跟上次选的值相同时弹出的窗口不会自动关闭，选不同的值时可以自动关闭，最好统一一下，加油

**Comment by lihongxun945** [comment]
和上次相同不就是没选么

**Comment by ZivZhao** [comment]
实际操作时，可能就是点开弹出后看了半天又想去选原来那个值， 不能像选其他值那样自动关闭， 要自己去点关闭 ，操作有差异，多了一步，当然这是从用户体验角度的建议

**Comment by lihongxun945** [comment]
我觉得又想去选原来的值，其实不就是没选么，这个时候更直接的操作是直接点“关闭”按钮，而不是去把之前选择的值再选一遍。

**Comment by ZivZhao** [comment]
好吧，这样也没毛病，如果选项挺多，产生滚动后，个人感觉直接关闭的效果比去点关闭体验能稍微好点，特别是手机屏幕比较大的情况下
