### ISSUE TITLE
Swiper和Popup并存时，Popup所在div被swiper对应的图片遮挡。

### ISSUE THREAD

**Issue by warman007** [lihongxun945/jquery-weui#75]
V0.6.1版本下，Swiper和Popup并存时，Popup内容页被swiper对应的图片遮挡。不知道如果这2个组件并存时，哪个组件显示在最前面？请检查对应的z-index。

**Comment by sy08400840** [comment]
貌似z-index问题不止你这一个情况，Swiper和Popup并存我还没用过，但是我用过tab和actionsheet并存在弹出actionsheet时会出现tab在最前面，因此必须在官方weui.css的tab中加 z-index: 0：
.weui_tab {
  position: relative;
  height: 100%;
  z-index: 0;/*原版无此行*/
}。
还有在用日历和官方select并存在弹出日历时会出现select元素显示在日历前面，也要在官方weui.css的select中将z-index: 1改成0：
.weui_select {
  -webkit-appearance: none;
  border: 0;
  outline: 0;
  background-color: transparent;
  width: 100%;
  font-size: inherit;
  height: 44px;
  line-height: 44px;
  position: relative;
  z-index: 0 /*原版值为1*/
  padding-left: 15px;
}

**Comment by lihongxun945** [comment]
看来zindex的配置确实有些问题，等我仔细看看。你们暂时可以在自己的项目中覆盖一下zindex来解决这个问题。
