### ISSUE TITLE
ActionSheet菜单能不能自定义样式，或者改变颜色？

### ISSUE THREAD

**Issue by rockjava** [lihongxun945/jquery-weui#76]
ActionSheet菜单能不能自定义样式，或者改变颜色？

**Comment by lihongxun945** [comment]
这个需求提的很好，我也正想改变文字颜色和增加图标的功能。预计下一个版本应该至少会加上自定义颜色的功能。

**Comment by rockjava** [comment]
需要的是菜单配置图标，菜单背景颜色自定义，菜单文字颜色自定义，有了这三个功能基本能满足大部分使用场景了

**Comment by lihongxun945** [comment]
在本周会发布一个新版本，支持自定义颜色和背景色。不过图标这个目前我没有找到好的参考，所以暂时不会加。

**Comment by lihongxun945** [comment]
`V0.7.0` 支持自定义文字颜色和背景色
