### ISSUE TITLE
搜索栏有一个BUG

### ISSUE THREAD

**Issue by huarse** [lihongxun945/jquery-weui#78]
* 操作1：点击搜索框，输入内容，点x清空，然后点空白处或取消，失去焦点，取消按钮隐藏；
* 操作2：点击搜索框，输入内容，直接点取消，失去焦点，但**取消按钮未隐藏**；再次获取焦点，然后失去焦点就隐藏了

**Comment by lihongxun945** [comment]
你说的bug是指第二步取消按钮未隐藏么，我在我的安卓和iphone上都未复现出这个问题。
你的系统版本是多少？

**Comment by huarse** [comment]
我在PC chrome里面模拟的
