### ISSUE TITLE
设备侦测工具 device.js 为什么比SUI还弱呢

### ISSUE THREAD

**Issue by gumutianqi** [lihongxun945/jquery-weui#79]
@lihongxun945 

设备侦测工具建议加入微信判断，以及微信版本判断，实现更贴近微信开发者的需求。

建议把card布局、侧滑菜单也从SUI搞过来。

准备加入到jquery-weui的强大阵营中！！！

建议整合扩展组件：
- [ ] 卡片布局
- [ ] Swipeout
- [ ] 滚动条
- [ ] 侧栏
- [ ] 标签页
- [ ] 音乐播放器；
- [ ] 全屏翻页，参考开源的swiper

工具类：
- [ ] JSSDK 整合过来；
- [ ] 图片上传前预览、旋转、放大缩小、裁剪工具；
- [ ] 音效操作工具类；
- [ ] 屏幕方向识别工具；
- [ ] 静态资源加载工具(图片、音频等)，如小游戏进入前的加载页处理；

**Comment by lihongxun945** [comment]
好多，你想要的大部分都会有的，只是需要几个月的开发时间。
而且设备检测这种我没有公布的API最好不要用，因为我后续可能会改掉。

**Comment by 99937272** [comment]
可以将vux里的组件移植过来^_^，这些组件写得不错
https://github.com/airyland/vux

**Comment by rockjava** [comment]
vux的组件确实不错，但使用起来难度有点大，所以我选用了jquery weui，希望weui组件日后越来越丰富

**Comment by gumutianqi** [comment]
@lihongxun945  vux的组件UI做得真心不错，建议可以在jquery-weui里面提供单独插件模版规范，让更多的人将优秀的模块整合进来，最后实现模块商店选择，自动打包

**Comment by lihongxun945** [comment]
@gumutianqi  你太乐观了，绝大部分用户并没有能力和意愿去花时间写一个合格的插件。

**Comment by lihongxun945** [comment]
而且其实根本不用提供商店什么的，如果有愿意贡献组件的完全可以通过 pull request 发给我。问题不不是在没有渠道，而是没有人愿意。
