### ISSUE TITLE
toast.js 中的一个undefined

### ISSUE THREAD

**Issue by xiongjiabin** [lihongxun945/jquery-weui#8]
var show = function(html, className) {

    var mask = $("<div class='weui_mask_transparent'></div>").appendTo(document.body);

    var tpl = '<div class="weui_toast ' + className + '">' + html + '</div>';
    var dialog = $(tpl).appendTo(document.body);

    dialog.show();
    dialog.addClass("weui_toast_visible");
  };

在toast.js 中， show没有带第二个参数className, 会导致这个地方有一个undefined class，
建议 改成

` var tpl = '<div class="weui_toast ' + className || "" + '">' + html + '</div>';`

**Comment by lihongxun945** [comment]
v0.4.0已经解决这个问题了
