### ISSUE TITLE
select 不能重复加载

### ISSUE THREAD

**Issue by fuhaoqiang** [lihongxun945/jquery-weui#85]
第一次加载如下代码
$("#employee").select({
			        title: "选择职业",
			        items: ["法官", "医生"],
			      });
第二次加载  如下代码
$("#employee").select({
			        title: "选择职业",
			        items: ["aaa", "bb"],
			        
			      });
第二次加载后，依然是第一次的结果。

希望实现功能，1、有移除所有功能，2、追加的功能

**Comment by lihongxun945** [comment]
这个建议很好，我会在下一个版本中加上一个更新数据的功能。应该是通过 `$(xxx).select("update", data)` 的方式来动态更新数据。

**Comment by wujiabin1983** [comment]
同问，急需

**Comment by fuhaoqiang** [comment]
delete input box  rebulit it

**Comment by lihongxun945** [comment]
@wujiabin1983  你可以在 `dev` 分支上看到最新的代码，还在开发中， `select("update", config)` 已经可以用了

**Comment by fuhaoqiang** [comment]
已经有更新了吗？

**Comment by lihongxun945** [comment]
没有更新到`master`，`dev` 只是一个开发分支

**Comment by fuhaoqiang** [comment]
我发现， calendar，日期控件，有选择不到日期的情况，在手机上面，每月的后几个日期选择时，没反应

**Comment by lihongxun945** [comment]
@fuhaoqiang  没听说这个问题，你可以提一个新的 issue，把手机的型号和微信的版本也说明一下。
另外你看下你的代码是不是最新版。

**Comment by wujiabin1983** [comment]
用了dev里面的select.js后，内容是可以更新了，但是菜单全部失效了。

**Comment by lihongxun945** [comment]
你是说点击了之后无法选择么？

**Comment by wujiabin1983** [comment]
第一次可以点开选项，就算没有操作直接点关闭选项，然后该菜单就再也点不开了。我在是正式版本上环境下，引入dev里面的select.js，不知道是否还需要引入其它文件  在线等

**Comment by lihongxun945** [comment]
@wujiabin1983  你需要自己编译一下，生成一个新的 `jquery-wei.js` 替换掉以前的版本。

**Comment by lihongxun945** [comment]
如果你是在旧的 `jquery-weui.js` 后面再引入 `select.js` 是一定有问题的。

**Comment by wujiabin1983** [comment]
明白，我试试，非谢感谢

**Comment by wujiabin1983** [comment]
OK，正常

**Comment by lihongxun945** [comment]
`V0.7.0` 已经解决了这个问题。
