### ISSUE TITLE
日期选择器，如果初始化给的value值不对，或为空，日历出来都是NaN

### ISSUE THREAD

**Issue by zqfleaf** [lihongxun945/jquery-weui#86]
安卓，微信里
日期选择器，如果初始化给的value值不对，或为空，日历出来都是NaN界面；
苹果上没有问题。

**Comment by sy08400840** [comment]
@zqfleaf 我跟你相反，一个红米，一个oppo都正常，但是同事的iphone4s显示全是NaN

**Comment by woshiguabi** [comment]
我也是IOS系全部NaN，不过加上当天的日期给value之后就可以使用了

**Comment by lihongxun945** [comment]
已经在 `dev` 分支上修复了这个问题，下一次发布新版本的时候就好了

**Comment by lihongxun945** [comment]
重复 [https://github.com/lihongxun945/jquery-weui/issues/71](https://github.com/lihongxun945/jquery-weui/issues/71)
