### ISSUE TITLE
为什么每次都是append呢

### ISSUE THREAD

**Issue by fishercoder** [lihongxun945/jquery-weui#9]
var dialog = $(tpl).appendTo(document.body);
每次都append，导致body里面有很多个diaolog。

**Comment by lihongxun945** [comment]
不会的，dialog关闭的时候会自动删除DOM的，而且dialog 逻辑上本来就不存在同时显示多个的问题。

**Comment by fishercoder** [comment]
$.confirm的时候，我点确认diaolog会关闭，但是其实不会清理掉。我自己在$.modal 里面添加了移除dom的代码，才算正常

**Comment by lihongxun945** [comment]
那就是你的用法有问题，或者是你没有引入 `jquery-weui.css`，或者是你影响了 confirm 的CSS动画。
我是在CSS动画结束后删除DOM的，你可以参见官网的DEMO，肯定是删除了的。

**Comment by fishercoder** [comment]
哦哦 ，那应该是我删除了weui_dialog 和opacity的原因了

**Comment by lihongxun945** [comment]
应该是的。没问题的话你把这个issue关了吧

**Comment by fishercoder** [comment]
我还以为这里就是简单的comment呢
