### ISSUE TITLE
Popup .weui-popup-container 需要增加 z-index:999;

### ISSUE THREAD

**Issue by victorylee** [lihongxun945/jquery-weui#94]
Popup 弹出时 如果页面上有 select控件的话  因为select的 z-index:1  会导致select的值显示在Popup上面。  所以需要设置  .weui-popup-container  z-index:999;

**Comment by lihongxun945** [comment]
感谢反馈，我会在下一个版本中修复这个问题。

**Comment by lihongxun945** [comment]
`V0.7.0` 已经解决了这个问题。
