### ISSUE TITLE
搜索栏控件

### ISSUE THREAD

**Issue by chang0022** [lihongxun945/jquery-weui#95]
回车方法：
```
    $(window).keyup(function(event) {
      if(event.keyCode == 13){
        var v = $('#search_input').val();
        console.log(v);
      }
    });
```
但是无法获取 `$('#search_input')`值，另外一个demo代码一样，但是需要断点能获取`$('#search_input')`值。我发现每次回车就好刷新页面，看源码没有找到对应方法。请问如何解决。

**Comment by chang0022** [comment]
我找到了原因，是键盘回车事件导致页面刷新的问题。可以采取两种方法解决这种问题：1.去掉表单；2.如果非得用表单，只要不让表单里有且只有一个文本框就OK了。所以我加了一个空的input 然后隐藏了。。。。。

**Comment by zbage** [comment]
前面提交过这个问题。
我的处理方式：
$('#search_input').keydown(function(e){
	if(e.keyCode==13){
		...
		e.preventDefault();
	}
});
