### ISSUE TITLE
请问picker里选择后如何进行回调呢？

### ISSUE THREAD

**Issue by 7PLonG** [lihongxun945/jquery-weui#96]
例：地址选择器 点击完成后，返回其选择值，供后台使用。
          还请大大们指点迷津

**Comment by liyandong** [comment]
同样想了解。

**Comment by lihongxun945** [comment]
可以在初始化的时候传入 `onClose` 参数，具体我会在下一次发布的时候加上文档说明。

**Comment by zhangchaoxu** [comment]
@lihongxun945 感谢提供如此好用的控件

根据实测，应该是在初始化picker的时候加入onClose参数。比如
`$("#picker").picker({
  title: "请选择您的手机",
  cols: [
    {
      textAlign: 'center',
onClose: function(data) {
            console.log("value:" + data.value);
            for(var i=0; i<data.value.length; i++){
                console.log("selected:" + data.value[i]);
            }
        },
      values: ['iPhone 4', 'iPhone 4S', 'iPhone 5', 'iPhone 5S', 'iPhone 6', 'iPhone 6 Plus', 'iPad 2', 'iPad Retina', 'iPad Air', 'iPad mini', 'iPad mini 2', 'iPad mini 3']
    }
  ]
});`
