### ISSUE TITLE
下一版本什么时候发布？

### ISSUE THREAD

**Issue by rockjava** [lihongxun945/jquery-weui#97]
下一版本什么时候发布？增加了哪些内容？能提交透露一下吗 ？

**Comment by lihongxun945** [comment]
已经发布了 `V0.7.0`，如果看不到的话 你可以刷新下官方。

**Comment by rockjava** [comment]
看到了，这个版本没有新增组件吧？
http://lihongxun945.github.io/jquery-weui/dist/demos/
在线示例，jquer-weui.js报错，1855行开始代码合并冲突

**Comment by lihongxun945** [comment]
@rockjava  刚才合并代码有问题，现在好了。有新增组件，你可以去[更新日志](https://github.com/lihongxun945/jquery-weui/blob/master/changelog.md)里面看
