### ISSUE TITLE
popup感觉运用不够灵活

### ISSUE THREAD

**Issue by karanatarm** [lihongxun945/jquery-weui#99]
我需要从底部出现，可设定高度，不用全遮。能点击其他地方，popup自动消失，可以灵活设置一些属性。希望在下一版本中，能看到这些改进。

**Comment by lihongxun945** [comment]
@karanatarm  这个建议非常好，不出意外的话下个版本应该会有的

**Comment by karanatarm** [comment]
@lihongxun945 jquery-weui组件都很好用，会继续支持，希望能开发更多实用组件

**Comment by zwl4488** [comment]
@lihongxun945 另外希望增加popover这样的气泡组件，配置丰富一点，加油~
